"""Generate every figure of the ESM paper (zero LLM, zero GPU).

Run from the repository root:
    python paper_figures/make_figs.py

Sources (read-only):
  * esm/results/heldout/results.json   (generated by esm.scripts.report_heldout)
  * esm/results/stream/results.json    (generated by esm.stream.report)
  * esm/results/heldout/revision_r1/item6.json (generated by item6_anchoring.py: taxonomy, episode
    counts); the per-episode lengths of fig_anchored are recomputed here with
    the same episode definition from esm/results/heldout/records.parquet (ESM-norepair, every commit)
    and the cached fact list esm/results/heldout/revision_r1/cache/meta.pkl (no LLM)
  * esm/results/datalake/results.json  (generated by esm.scripts.report_datalake: T1|dl_tlc|R,
    T1|dl_bb|ALL, T9)
  * esm/results/heldout/revision_r1_runs/results.json (generated by revision_r1_runs/analyze.py: NAT100
    natural-sample run and the real anchor-expiry run; fig_natural, fig_expiry = Supplementary Figs. S5, S6)
  * esm/results/heldout/revision_r2/repeat_error.json (fig_anchored panel d, consecutive derivation pairs)
  * esm/results/heldout/revision_r3/estimate_c.json (generated by revision_r3/estimate_c.py: anchor-expiry
    estimate C with the consecutive-pair statistic; fig_expiry = Supplementary Fig. S6)
  * esm/results/e2e/results.json and esm/results/e2e_lake/results.json (ESWA B3 end-to-end task evaluations,
    generated by esm.e2e.report_e2e / esm.e2e_lake.report_lake; fig_e2e)
  * the pilot studies behind the negative results (Section 4 of the paper; not part of this
    repository): their numbers are copied below as constants, each with the table it comes from.
"""
import json
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.patches import FancyBboxPatch  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.environ.get("ESM_FIG_OUT", os.path.dirname(os.path.abspath(__file__)))
HO = json.load(open(os.path.join(ROOT, "esm/results/heldout/results.json"), encoding="utf-8"))
ST = json.load(open(os.path.join(ROOT, "esm/results/stream/results.json"), encoding="utf-8"))

# Okabe-Ito colour-blind-safe palette
OI = dict(black="#000000", orange="#E69F00", sky="#56B4E9", green="#009E73",
          yellow="#F0E442", blue="#0072B2", red="#D55E00", purple="#CC79A7", grey="#999999")

plt.rcParams.update({
    "font.family": "serif", "font.size": 7.5, "axes.titlesize": 7.5, "axes.labelsize": 7.5,
    "xtick.labelsize": 6.5, "ytick.labelsize": 6.5, "legend.fontsize": 6.2,
    "axes.spines.top": False, "axes.spines.right": False, "pdf.fonttype": 42,
    "axes.linewidth": 0.6, "xtick.major.width": 0.6, "ytick.major.width": 0.6,
})
COL = 3.45   # single column width (in)
FULL = 7.1   # double column width (in)


def save(fig, name):
    fig.savefig(os.path.join(OUT, name), bbox_inches="tight", pad_inches=0.02)
    if os.environ.get("FIG_PREVIEW"):  # optional PNG previews for visual checks
        fig.savefig(os.path.join(os.environ["FIG_PREVIEW"], name.replace(".pdf", ".png")),
                    bbox_inches="tight", pad_inches=0.02, dpi=220)
    plt.close(fig)
    print("wrote", name)


# ---------------------------------------------------------------- 1. method overview
def fig_method():
    fig, ax = plt.subplots(figsize=(FULL, 2.3))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 31)
    ax.axis("off")

    def box(x, y, w, h, text, fc, fs=6.0, bold=False):
        p = FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.2,rounding_size=0.8",
                           fc=fc, ec="#333333", lw=0.7)
        ax.add_patch(p)
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fs,
                fontweight="bold" if bold else "normal")

    def arrow(x0, y0, x1, y1, text=None, tx=None, ty=None, color="#333333"):
        ax.annotate("", xy=(x1, y1), xytext=(x0, y0),
                    arrowprops=dict(arrowstyle="-|>", lw=0.8, color=color, shrinkA=0, shrinkB=0))
        if text:
            ax.text(tx, ty, text, fontsize=5.6, ha="center", va="center", color=color)

    blue, yel, grey, green, pink, orng = "#EAF3FB", "#FFF4D6", "#F2F2F2", "#DFF2E9", "#FCE4EC", "#FDE2CF"
    ax.plot([20.5, 20.5], [0.3, 30.5], ls=":", lw=0.7, color="#888888")
    ax.text(10, 29.8, "derivation (version $s_0$)", ha="center", fontsize=6.3, style="italic")
    ax.text(60, 29.8, "every later read (version $s_t$)", ha="center", fontsize=6.3, style="italic")
    # left column
    box(1, 20, 18, 7.5, "LLM agent derives K\nthrough deterministic\ntool calls (trace)", blue)
    box(1, 10, 18, 7.5, "(1) record evidence:\nanchor calls by symbol,\ncontent or key", yel)
    box(1, 0.8, 18, 6.5, "store K, anchored\nqueries, state $e_0$", grey)
    arrow(10, 19.6, 10, 17.9)
    arrow(10, 9.6, 10, 7.7)
    # top row
    box(23.5, 20, 15, 7.5, "(2) replay anchored\nqueries (no LLM),\ngiving state $e_t$", blue)
    ax.annotate("", xy=(31, 19.6), xytext=(19.4, 4.0),
                arrowprops=dict(arrowstyle="-|>", lw=0.8, color="#333333",
                                connectionstyle="angle,angleA=0,angleB=90,rad=0"))
    box(43, 20, 13, 7.5, "$e_t$ equal to\nanchor state?", grey, bold=True)
    arrow(38.9, 23.75, 42.6, 23.75)
    box(62, 20, 15, 7.5, "reuse K\n(no LLM tokens)", green)
    arrow(56.4, 23.75, 61.6, 23.75, "yes", 59, 25.3, OI["green"])
    # middle row
    box(40, 9.5, 19, 8, "(3) memo hit on\n(anchor, $e_t$)? else build\nfocused delta; split\nhierarchically if large", yel, fs=5.8)
    arrow(49.5, 19.6, 49.5, 17.9, "no", 51.5, 18.8, OI["red"])
    box(63.5, 9.5, 12.5, 8, "LLM judge:\nstill_valid |\nchanged | unsure", pink)
    arrow(59.4, 13.5, 63.1, 13.5)
    arrow(69.75, 17.9, 69.75, 19.6, "still_valid", 73.6, 18.7, OI["green"])
    box(83, 9.5, 16, 8, "(4) re-derive with\nthe agent at $s_t$;\nnew K, new anchor", orng)
    arrow(76.4, 13.5, 82.6, 13.5, "changed /\nunsure", 79.5, 10.4, OI["red"])
    # bottom
    box(83, 0.8, 16, 6.2, "(5) memoise verdict\nper (anchor, state)", grey)
    arrow(69.75, 9.1, 82.6, 4.0)
    ax.text(51, 3.6, "LLM cost grows with the number of distinct\nevidence states, not with reads or commits",
            fontsize=5.8, ha="center", va="center", color="#333333", style="italic")
    save(fig, "fig_method.pdf")


# ---------------------------------------------------------------- 2. negative results
def fig_negative():
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(FULL, 2.05), gridspec_kw=dict(width_ratios=[1, 1.25]))
    # (a) coverage of future-unsound guards (pilot5/RESULTS.md, section 4.1, n = 222)
    labels = ["history, 4 audits", "full history (300)", "generic mutants", "LLM mutants",
              "LLM+gen., LLM-valid", "LLM+gen., oracle-valid"]
    vals = [28.4, 44.1, 72.5, 92.3, 75.2, 94.6]
    cols = [OI["grey"], OI["grey"], OI["sky"], OI["blue"], OI["orange"], OI["blue"]]
    y = range(len(labels))
    a1.barh(y, vals, color=cols, height=0.62)
    for i, v in enumerate(vals):
        a1.text(v + 1.2, i, f"{v:.1f}", va="center", fontsize=6.2)
    a1.set_yticks(list(y))
    a1.set_yticklabels(labels)
    a1.set_xlim(0, 108)
    a1.set_xlabel("future-unsound guards refuted (%)")
    a1.set_title("(a) Who can refute an unsound guard? (n = 222)", loc="left")

    # (b) blind validator recall by change kind, 27B (pilot6/RESULTS.md, section 4)
    kinds = ["value edit", "logic change", "add items", "dependency change", "syntax form",
             "remove symbol", "merge/split", "move definition", "rename symbol", "file move",
             "alias/re-export", "override/shadow", "file delete"]
    rec = [95, 96, 90, 86, 77, 64, 61, 59, 57, 56, 55, 44, 33]
    structural = {"remove symbol", "merge/split", "move definition", "rename symbol", "file move",
                  "alias/re-export", "override/shadow", "file delete"}
    c = [OI["red"] if k in structural else OI["green"] for k in kinds]
    x = range(len(kinds))
    a2.bar(x, rec, color=c, width=0.7)
    a2.set_xticks(list(x))
    a2.set_xticklabels(kinds, rotation=55, ha="right", fontsize=5.9)
    a2.set_ylim(0, 105)
    a2.set_ylabel("validator recall (%)")
    a2.set_title("(b) Blind 27B validator recall by kind of real change", loc="left")
    from matplotlib.patches import Patch
    a2.legend(handles=[Patch(color=OI["green"], label="content edits"),
                       Patch(color=OI["red"], label="structural edits")],
              loc="upper right", frameon=False)
    fig.tight_layout(w_pad=1.5)
    save(fig, "fig_negative.pdf")


# ---------------------------------------------------------------- 3. held-out Pareto
LABEL = {"ESM-norepair": "ESM", "ESM-verify": "ESM-verify", "ESM": "ESM, plain repair",
         "NEVER": "NEVER", "TTL50": "TTL50", "TTL100": "TTL100", "TTL200": "TTL200",
         "REPLAY": "REPLAY", "CERT-ZS": "CERT-ZS", "LLMDIFF": "LLMDIFF",
         "ESM-norepair-noanchor": "ESM, no anchoring", "ESM-norepair-9B": "ESM, 9B judge",
         "ESM-norepair-n2": "ESM, n=2 self-cons.", "ESM-norepair-9Bderiver": "ESM, 9B deriver"}


def fig_pareto_heldout():
    t = HO["T1c"]
    fig, ax = plt.subplots(figsize=(COL, 2.5))
    base = ["NEVER", "TTL200", "TTL100", "TTL50", "REPLAY", "CERT-ZS", "LLMDIFF"]
    esm = ["ESM-norepair", "ESM-verify"]
    abl = []
    orc = ["REPLAY@oracle", "TTL50@oracle", "ESM-norepair@oracle"]

    def xv(k):
        return max(t[k]["tok_per_fact"] / 1000.0, 6.0)  # NEVER (0 tokens) drawn at the left edge

    for k in base:
        r = t[k]
        lo, hi = r["sw_ci"]
        ax.errorbar(xv(k), 100 * r["sw"], yerr=[[100 * (r["sw"] - lo)], [100 * (hi - r["sw"])]],
                    fmt="o", ms=4, color=OI["blue"], ecolor=OI["blue"], elinewidth=0.6, capsize=1.5)
    for k in esm:
        r = t[k]
        lo, hi = r["sw_ci"]
        ax.errorbar(xv(k), 100 * r["sw"], yerr=[[100 * (r["sw"] - lo)], [100 * (hi - r["sw"])]],
                    fmt="*" if k == "ESM-norepair" else "D", ms=8 if k == "ESM-norepair" else 4,
                    color=OI["red"], ecolor=OI["red"], elinewidth=0.6, capsize=1.5)
    for k in abl:
        r = t[k]
        ax.plot(xv(k), 100 * r["sw"], "^", ms=3.5, color=OI["orange"])
    for k in orc:
        r = t[k]
        ax.plot(xv(k), 100 * r["sw"], "s", ms=3.5, mfc="none", mec=OI["grey"], mew=0.8)
    # label offsets in points (dx, dy), chosen by hand to avoid overlaps
    offs = {"NEVER": (5, 0), "TTL200": (5, 0), "TTL100": (5, 0), "TTL50": (5, 1), "REPLAY": (0, 9),
            "CERT-ZS": (0, -9), "LLMDIFF": (6, -5), "ESM-norepair": (0, -15), "ESM-verify": (-6, 3)}
    for k, (dx, dy) in offs.items():
        ha = "left" if dx > 0 else ("right" if dx < 0 else "center")
        ax.annotate(LABEL[k], (xv(k), 100 * t[k]["sw"]), xytext=(dx, dy), textcoords="offset points",
                    fontsize=5.8, ha=ha, va="center", color=OI["red"] if k.startswith("ESM") else "black")
    for k, lab, dx, dy in [("REPLAY@oracle", "REPLAY@oracle", -5, 4), ("ESM-norepair@oracle", "ESM@oracle", 5, 0),
                           ("TTL50@oracle", "TTL50@oracle", 5, -2)]:
        ax.annotate(lab, (xv(k), 100 * t[k]["sw"]), xytext=(dx, dy), ha="right" if dx < 0 else "left",
                    va="center", textcoords="offset points", fontsize=5.2, color="#666666")
    ax.set_xscale("log")
    ax.set_xlim(5, 300)
    ax.set_ylim(-1.5, 36)
    ax.set_xticks([6, 10, 20, 50, 100, 200])
    ax.set_xticklabels(["0", "10", "20", "50", "100", "200"])
    ax.minorticks_off()
    ax.set_xlabel("LLM tokens per fact, 400 commits (thousands, log)")
    ax.set_ylabel("served-wrong reads (%)")
    ax.grid(True, which="major", lw=0.3, alpha=0.5)
    save(fig, "fig_pareto_heldout.pdf")


# ---------------------------------------------------------------- 4. detection ablation
def fig_detection():
    t = HO["T5"]
    rows = [("DETECT-p7a|H150", "pilot7\ntriage"),
            ("DETECT-noanchor-hier|H150", "no anchor\n+ hier."),
            ("DETECT-anchor-trunc|H150", "anchor\n+ trunc."),
            ("DETECT-anchor-hier|H150", "ESM\n(anchor+hier.)"),
            ("DETECT-9B|H150", "ESM,\n9B judge")]
    fig, ax = plt.subplots(figsize=(COL, 2.1))
    import numpy as np
    x = np.arange(len(rows))
    w = 0.38
    for j, (met, col, lab) in enumerate([("ff", OI["red"], "false-fresh (FF)"), ("fs", OI["blue"], "false-stale (FS)")]):
        vals, lo, hi = [], [], []
        for key, _ in rows:
            r = t[key]["all"]
            vals.append(100 * r[met])
            lo.append(100 * (r[met] - r[met + "_ci"][0]))
            hi.append(100 * (r[met + "_ci"][1] - r[met]))
        ax.bar(x + (j - 0.5) * w, vals, w, yerr=[lo, hi], color=col, label=lab,
               error_kw=dict(elinewidth=0.6, capsize=1.5))
        for i, v in enumerate(vals):
            ax.text(x[i] + (j - 0.5) * w, v + hi[i] + 0.4, f"{v:.1f}", ha="center", fontsize=5.3)
    ax.set_xticks(x)
    ax.set_xticklabels([r[1] for r in rows], fontsize=5.6)
    ax.set_ylabel("per-commit rate (%), S160")
    ax.set_ylim(0, 26)
    ax.legend(frameon=False, loc="upper left", ncol=2)
    save(fig, "fig_detection.pdf")


# ---------------------------------------------------------------- 5. schedules + re-derivation accuracy
def fig_schedules():
    t4 = HO["T4"]
    sch = [("every", "every\n(400)"), ("every5", "every5\n(80)"), ("bursty", "bursty\n(80)"),
           ("every20", "every20\n(20)"), ("every50", "every50\n(8)")]
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(FULL, 1.95), gridspec_kw=dict(width_ratios=[1.1, 1]))
    import numpy as np
    x = np.arange(len(sch))

    def rec(s):  # every-commit H150 lives in T1c, sparse schedules in T4
        return HO["T1c"]["ESM-norepair"] if s == "every" else t4[f"ESM-norepair|{s}|H150"]
    sw = [100 * rec(s)["sw"] for s, _ in sch]
    tpr = [rec(s)["tok_per_read"] for s, _ in sch]
    tpf = [rec(s)["tok_per_fact"] / 1000 for s, _ in sch]
    a1.bar(x - 0.2, tpf, 0.4, color=OI["blue"], label="tokens per fact (k)")
    a1.set_ylabel("tokens per fact (thousands)")
    a1.set_xticks(x)
    a1.set_xticklabels([s[1] for s in sch])
    a1b = a1.twinx()
    a1b.spines["right"].set_visible(True)
    a1b.bar(x + 0.2, tpr, 0.4, color=OI["orange"], label="tokens per read")
    a1b.set_yscale("log")
    a1b.set_ylabel("tokens per read (log)")
    for i in range(len(sch)):
        a1.text(x[i] - 0.2, tpf[i] + 0.4, f"{sw[i]:.1f}%", ha="center", fontsize=5.4, color=OI["red"])
    a1.set_ylim(0, 31)
    h1, l1 = a1.get_legend_handles_labels()
    h2, l2 = a1b.get_legend_handles_labels()
    a1.legend(h1 + h2, l1 + l2, frameon=False, loc="upper center", ncol=2, bbox_to_anchor=(0.5, 1.13))
    a1.set_title("(a) ESM on S160 by read schedule (red: served-wrong)", loc="left", pad=12)

    t6 = HO["T6"]
    grid = [50, 100, 150, 200, 250, 300, 350, 400]
    for model, col, mk in [("27B", OI["blue"], "o"), ("9B", OI["orange"], "s")]:
        acc = [100 * t6[model][f"grid t = {g}"]["acc"] for g in grid]
        a2.plot(grid, acc, marker=mk, ms=3, color=col, lw=1, label=f"{model} agent")
    a2.set_xlabel("FUTURE commit index t (S160 grid)")
    a2.set_ylabel("re-derivation correct (%)")
    a2.set_ylim(70, 101)
    a2.legend(frameon=False, loc="lower left")
    a2.grid(True, lw=0.3, alpha=0.5)
    a2.set_title("(b) Accuracy of fresh re-derivations decays", loc="left")
    fig.tight_layout(w_pad=2.2)
    save(fig, "fig_schedules.pdf")


# ---------------------------------------------------------------- 6. stream Pareto
def fig_stream():
    real = ST["T5_poisson_H150"]["real"]
    pois = ST["T5_poisson_H150"]["poisson"]
    keys = [("ESM-norepair", "ESM"), ("ESM-verify", "ESM-verify"), ("NEVER", "NEVER"),
            ("TTL50", "TTL50"), ("TTL100", "TTL100"), ("TTL200", "TTL200"), ("REPLAY", "REPLAY"),
            ("CERT-ZS", "CERT-ZS"), ("LLMDIFF", "LLMDIFF"), ("FILEHASH*", "FILEHASH*"), ("ALWAYS*", "ALWAYS*")]
    orc = [("ESM-norepair@oracle", "ESM@oracle"), ("REPLAY@oracle", "REPLAY@oracle"), ("ALWAYS@oracle", "ALWAYS@oracle")]
    fig, ax = plt.subplots(figsize=(COL, 2.45))

    def xv(r):
        return max(r["tok_task"], 40)

    offs = {"ESM": (-4, -6), "ESM-verify": (-4, 5), "NEVER": (4, 0), "TTL50": (4, 2), "TTL100": (4, 0),
            "TTL200": (4, 0), "REPLAY": (4, 2), "CERT-ZS": (4, -3), "LLMDIFF": (4, 3), "FILEHASH*": (4, -3),
            "ALWAYS*": (-4, 6)}
    for k, lab in keys:
        if k not in real:
            continue
        r, p = real[k], pois[k]
        isesm = k.startswith("ESM")
        col = OI["red"] if isesm else OI["blue"]
        lo, hi = r["wt_ci"]
        ax.errorbar(xv(r), 100 * r["wt"], yerr=[[100 * (r["wt"] - lo)], [100 * (hi - r["wt"])]],
                    fmt="*" if k == "ESM-norepair" else "o", ms=7 if k == "ESM-norepair" else 3.6,
                    color=col, elinewidth=0.5, capsize=1.2, alpha=0.95)
        ax.plot(xv(p), 100 * p["wt"], "o", ms=3.6, mfc="none", mec=col, mew=0.7)
        dx, dy = offs[lab]
        ax.annotate(lab, (xv(r), 100 * r["wt"]), xytext=(dx, dy), textcoords="offset points", fontsize=5.4,
                    ha="left" if dx > 0 else "right", va="center")
    for k, lab in orc:
        r = real[k]
        ax.plot(xv(r), 100 * r["wt"], "s", ms=3.4, mfc="none", mec=OI["grey"], mew=0.8)
        ax.annotate(lab, (xv(r), 100 * r["wt"]), xytext=(3, 4), textcoords="offset points", fontsize=5.0, color="#666666")
    ax.set_xscale("log")
    ax.set_xlim(30, 30000)
    ax.set_ylim(-2, 50)
    ax.set_xlabel("LLM tokens per task (log; NEVER = 0 drawn at left edge)")
    ax.set_ylabel("tasks served a wrong answer (%)")
    ax.grid(True, which="major", lw=0.3, alpha=0.5)
    ax.plot([], [], "o", color="k", ms=3.5, label="real issue arrivals")
    ax.plot([], [], "o", mfc="none", mec="k", ms=3.5, label="rate-matched Poisson")
    ax.plot([], [], "s", mfc="none", mec=OI["grey"], ms=3.5, label="@oracle (idealised)")
    ax.legend(frameon=False, loc="upper right", fontsize=5.6)
    save(fig, "fig_stream.pdf")


# ---------------------------------------------------------------- 7. anchored wrong re-derivations
R1 = os.path.join(ROOT, "esm/results/heldout/revision_r1")


def anchored_episodes():
    """Wrong-served episodes of ESM (frozen = ESM-norepair), ALL, every commit, with exactly the definition of
    esm/results/heldout/revision_r1/item6_anchoring.py (part A2): an episode is a maximal run of consecutive
    wrong-served reads of one fact; its cause is the action at its first read; its length is the number of commits
    until the next right read (401 - start if it is still wrong at t = 400, i.e. censored)."""
    import pickle
    import pandas as pd
    meta = pickle.load(open(os.path.join(R1, "cache", "meta.pkl"), "rb"))
    ids = {f["iid"] for f in meta["facts"]}
    d = pd.read_parquet(os.path.join(ROOT, "esm/results/heldout/records.parquet"),
                        filters=[("policy", "==", "ESM-norepair"), ("schedule", "==", "every")],
                        columns=["iid", "t", "action", "served_valid"])
    d = d[d.iid.isin(ids)].sort_values(["iid", "t"]).reset_index(drop=True)
    eps = []
    for _, x in d.groupby("iid", sort=False):
        sv, ac, ts = x.served_valid.to_numpy(), x.action.to_numpy(), x.t.to_numpy()
        k = 0
        while k < len(sv):
            if sv[k]:
                k += 1
                continue
            s = k
            while k < len(sv) and not sv[k]:
                k += 1
            cause = ("wrong re-derivation" if ac[s] == "rederive" else "memo still_valid" if ac[s] == "memo"
                     else "evidence unchanged" if ac[s] == "same" else "judge valid")
            end = int(ts[k]) if k < len(sv) else 401
            eps.append(dict(cause=cause, len=end - int(ts[s]), reads=k - s, censored=k == len(sv)))
    return pd.DataFrame(eps)


def fig_anchored():
    import numpy as np
    i6 = json.load(open(os.path.join(R1, "item6.json"), encoding="utf-8"))
    E = anchored_episodes()
    W = E[E.cause == "wrong re-derivation"]
    # consistency with the generated report (item6.json / item6.md section 6b)
    assert len(E) == i6["episodes_n"] and len(W) == i6["wrong_rederive_eps"]["n"], "episode recount differs from item6.json"
    assert W.len.median() == i6["wrong_rederive_eps"]["q"][2]
    fig, axs = plt.subplots(1, 4, figsize=(FULL, 2.2), gridspec_kw=dict(width_ratios=[0.92, 1.05, 1.05, 1.2]))
    a1, a2, a3, a4 = axs

    # (a) read-level causes, split by oracle NONE / present (heldout results.json)
    tax = HO["taxonomy|ESM-norepair"]
    causes = [("persisting wrong rederive", "wrong re-derivation,\npersisting"),
              ("wrong re-derivation (agent answer wrong)", "wrong re-derivation,\nfirst read"),
              ("missed: memoised still_valid reused on a state whose truth differs", "memoised still_valid\non changed truth"),
              ("missed: judge said still_valid on a changed state", "judge still_valid\non changed state"),
              ("missed: evidence state unchanged (change outside the recorded evidence)", "change outside\nrecorded evidence")]
    y = np.arange(len(causes))[::-1]
    none = [tax.get(f"{c} | truth NONE", {"reads": 0})["reads"] / 1000 for c, _ in causes]
    pres = [tax.get(f"{c} | truth present", {"reads": 0})["reads"] / 1000 for c, _ in causes]
    a1.barh(y, none, color=OI["red"], height=0.6, label="oracle NONE")
    a1.barh(y, pres, left=none, color=OI["blue"], height=0.6, label="referent present")
    for i in range(len(causes)):
        tot = none[i] + pres[i]
        a1.text(tot + 0.4, y[i], f"{1000 * tot:,.0f}", va="center", fontsize=5.4)
    a1.set_yticks(y)
    a1.set_yticklabels([c[1] for c in causes], fontsize=5.6)
    a1.set_xlabel("wrong-served reads (k), ALL, every commit", fontsize=6.2)
    a1.set_xlim(0, 38)
    a1.set_xticks([0, 10, 20, 30])
    a1.legend(frameon=False, loc="lower right", fontsize=5.1, handlelength=0.9, borderaxespad=0.1)
    a1.set_title("(a) Wrong-served reads by cause", loc="left", fontsize=6.2)

    # (b) episode-level decomposition (same episodes as item6.md section 6b)
    order = [("wrong re-derivation", "wrong re-\nderivation"), ("judge valid", "judge\nvalid"),
             ("memo still_valid", "memo\nstill_valid"), ("evidence unchanged", "evidence\nunchanged")]
    ne, nr = len(E), E.reads.sum()
    pe = [100 * (E.cause == c).sum() / ne for c, _ in order]
    pr = [100 * E[E.cause == c].reads.sum() / nr for c, _ in order]
    cnt = [int((E.cause == c).sum()) for c, _ in order]
    yb = np.arange(len(order))[::-1]
    h = 0.38
    a2.barh(yb + h / 2, pe, h, color=OI["orange"], label="% of episodes")
    a2.barh(yb - h / 2, pr, h, color=OI["red"], label="% of wrong reads")
    for i in range(len(order)):
        a2.text(pe[i] + 1.5, yb[i] + h / 2, f"{pe[i]:.1f}", va="center", fontsize=5.0)
        a2.text(pr[i] + 1.5, yb[i] - h / 2, f"{pr[i]:.1f}", va="center", fontsize=5.0)
    a2.set_yticks(yb)
    a2.set_yticklabels([f"{o[1]}\n({n} ep.)" for o, n in zip(order, cnt)], fontsize=5.0, linespacing=1.05)
    a2.set_xlim(0, 112)
    a2.set_xticks([0, 25, 50, 75, 100])
    a2.set_xlabel("share (%)", fontsize=6.2)
    a2.legend(frameon=False, loc="lower right", fontsize=5.1, handlelength=1.0, borderaxespad=0.1)
    a2.set_title(f"(b) Episodes vs reads ({ne} episodes)", loc="left", fontsize=6.2)

    # (c) episode length distribution
    bins = np.arange(0, 420, 20)
    a3.hist(W.len, bins=bins, color=OI["red"], alpha=0.85)
    a3.hist(E[E.cause != "wrong re-derivation"].len, bins=bins, color=OI["blue"], alpha=0.6)
    a3.text(400, 67, f"wrong re-derivation\n({len(W)} ep.), {100 * W.censored.mean():.0f} % still\nwrong at t = 400",
            color=OI["red"], fontsize=5.2, ha="right", va="center")
    a3.text(24, 54, f"other causes ({len(E) - len(W)} ep.)", color=OI["blue"], fontsize=5.2, ha="left", va="center")
    med = W.len.median()
    a3.plot([med, med], [0, 50], color="#333333", ls="--", lw=0.7)
    a3.text(med + 5, 33, f"median {med:.0f}", fontsize=5.2, va="center", ha="left", rotation=90)
    a3.set_xlim(0, 400)
    a3.set_xticks([0, 100, 200, 300, 400])
    a3.set_ylim(0, 76)
    a3.set_yticks([0, 20, 40, 60])
    a3.set_xlabel("episode length (commits)", fontsize=6.2)
    a3.set_ylabel("episodes", fontsize=6.2)
    a3.set_title("(c) Episode length", loc="left", fontsize=6.2)

    # (d) P(next derivation of the same fact correct | previous one wrong, truth unchanged in between), revision r2
    # (revision_r2/repeat_error.json): consecutive derivations only, (i) main ESM run (s0 + its re-derivations, ALL) and
    # (ii) every real arm, each (fact, commit) derivation counted once.  Pooled over pairs (repository-cluster CI) and
    # with each fact weighted equally (fact CI).  Round 1 plotted all later pairs (7,390; quadratic in derivations/fact).
    rr = json.load(open(os.path.join(ROOT, "esm/results/heldout/revision_r2/repeat_error.json"), encoding="utf-8"))
    grp = [("E", "main run"), ("C", "all arms")]
    x = np.arange(len(grp))
    w = 0.36
    for j, (k, _) in enumerate(grp):
        r_ = rr[k]
        for dx, val, ci, col in ((-w / 2, r_["p_right_after_wrong"], r_["repo_ci"], OI["red"]),
                                 (w / 2, r_["fact_mean"], r_["fact_mean_ci"], OI["orange"])):
            v = 100 * val
            a4.bar(x[j] + dx, v, w, color=col, label=None)
            a4.errorbar(x[j] + dx, v, yerr=[[v - 100 * ci[0]], [100 * ci[1] - v]], color="#333333", lw=0.6, capsize=1.5)
            a4.text(x[j] + dx, 100 * ci[1] + 2.5, f"{v:.1f}", ha="center", fontsize=5.2)
        a4.text(x[j], 46, f"{r_['pairs_wrong_unch']} pairs\n{r_['facts']} facts", ha="center", fontsize=4.9, color="#555555")
    ref = 100 * rr["E"]["p_right_after_right"]
    a4.axhline(ref, color=OI["grey"], ls="--", lw=0.7)
    a4.text(1.62, ref - 3, f"after a right one: {ref:.0f}–{100 * rr['C']['p_right_after_right']:.0f} %", ha="right", va="top", fontsize=4.9, color="#555555")
    a4.bar([0], [0], color=OI["red"], label="pooled pairs")
    a4.bar([0], [0], color=OI["orange"], label="per fact")
    a4.legend(frameon=False, loc="upper left", fontsize=5.0, handlelength=0.9, borderaxespad=0.1, bbox_to_anchor=(0.0, 0.86))
    a4.set_xticks(x)
    a4.set_xticklabels([g[1] for g in grp], fontsize=5.6)
    a4.set_ylim(0, 105)
    a4.set_xlim(-0.6, 1.65)
    a4.set_yticks([0, 25, 50, 75, 100])
    a4.set_ylabel("next derivation correct (%)", fontsize=6.0)
    a4.set_xlabel("previous derivation wrong,\ntruth unchanged", fontsize=6.0)
    a4.set_title("(d) Asking again after an error", loc="left", fontsize=6.2)
    fig.tight_layout(w_pad=1.0, rect=(0, 0, 0.99, 1))
    # four long titles on a narrow grid: start each title at the left edge of its panel's tick labels
    fig.canvas.draw()
    r = fig.canvas.get_renderer()
    for ax in axs:
        bb, tb = ax.get_window_extent(r), ax.get_tightbbox(r)
        ax.set_title(ax.get_title(loc="left"), loc="left", fontsize=6.2, x=(tb.x0 - bb.x0) / bb.width)
    save(fig, "fig_anchored.pdf")


# ---------------------------------------------------------------- 8. data lake
DL = json.load(open(os.path.join(ROOT, "esm/results/datalake/results.json"), encoding="utf-8"))


def _lake_pareto(ax, t, ttls, offs, title):
    """served-wrong % vs LLM tokens per fact (thousands, log); NEVER (0 tokens) drawn at the left edge."""
    def xv(k):
        return max(t[k]["tok_per_fact"] / 1000.0, 7.0)

    for k, col, fmt, ms in [("NEVER", OI["blue"], "o", 4), ("ESM-norepair", OI["red"], "*", 8)]:
        r = t[k]
        lo, hi = r["sw_ci"]
        ax.errorbar(xv(k), 100 * r["sw"], yerr=[[100 * (r["sw"] - lo)], [100 * (hi - r["sw"])]],
                    fmt=fmt, ms=ms, color=col, ecolor=col, elinewidth=0.6, capsize=1.5)
    refs = [f"{x}@oracle" for x in ttls] + ["FILEHASH@oracle", "REPLAY@oracle"]
    for k in refs:
        ax.plot(xv(k), 100 * t[k]["sw"], "s", ms=3.5, mfc="none", mec=OI["grey"], mew=0.8)
    names = {"NEVER": "NEVER", "ESM-norepair": "ESM", "REPLAY@oracle": "REPLAY/MANIFEST\n@oracle"}
    for k, (dx, dy) in offs.items():
        ha = "left" if dx > 0 else ("right" if dx < 0 else "center")
        isref = "@oracle" in k
        lab = names.get(k, k)
        if isref and dx <= 0 and "\n" not in lab:  # labels left of / below a marker: two lines to stay narrow
            lab = lab.replace("@oracle", "\n@oracle")
        ax.annotate(lab, (xv(k), 100 * t[k]["sw"]), xytext=(dx, dy), textcoords="offset points",
                    fontsize=5.0 if isref else 5.8, ha=ha, va="center",
                    color="#666666" if isref else (OI["red"] if k.startswith("ESM") else "black"))
    ax.set_xscale("log")
    ax.set_xlim(5, 12000)
    ax.set_xticks([7, 100, 1000, 10000])
    ax.set_xticklabels(["0", "100", "1k", "10k"])
    ax.minorticks_off()
    ax.set_xlabel("LLM tokens per fact (thousands, log)", fontsize=6.2)
    ax.grid(True, which="major", lw=0.3, alpha=0.5)
    ax.set_title(title, loc="left", fontsize=6.8)


def fig_lake():
    import numpy as np
    fig, (a1, a2, a3) = plt.subplots(1, 3, figsize=(FULL, 2.2), gridspec_kw=dict(width_ratios=[1, 1, 1.55]))
    _lake_pareto(a1, DL["T1|dl_tlc|R"], ["TTL25", "TTL50", "TTL100"],
                 {"NEVER": (5, 0), "ESM-norepair": (6, 3), "TTL25@oracle": (5, -4), "TTL50@oracle": (-5, -4),
                  "TTL100@oracle": (-5, 0), "FILEHASH@oracle": (5, 0), "REPLAY@oracle": (0, 9)},
                 "(a) TLC (115 facts, 229 snapshots)")
    a1.set_ylim(-3, 45)
    a1.set_ylabel("served-wrong reads (%)")
    _lake_pareto(a2, DL["T1|dl_bb|ALL"], ["TTL20", "TTL40", "TTL100"],
                 {"NEVER": (4, 7), "ESM-norepair": (-6, -2), "TTL20@oracle": (0, -7), "TTL40@oracle": (5, 3),
                  "TTL100@oracle": (5, -5), "FILEHASH@oracle": (5, 3), "REPLAY@oracle": (0, 9)},
                 "(b) Backblaze (57 facts, 105 snapshots)")
    a2.set_ylim(-3, 45)

    # (c) real TLC schema events (T9): served-wrong % of affected facts' reads in the 10 snapshots from the event
    short = {48: "yellow 23-02", 49: "green 23-02", 50: "fhv 23-02", 51: "fhvhv 23-02", 94: "zones",
             145: "yellow 25-01", 146: "green 25-01", 148: "fhvhv 25-01", 219: "yellow 26-06", 220: "green 26-06"}
    ev = {}
    for r in DL["T9"]:
        if r["lake"] == "dl_tlc":
            ev.setdefault((r["t"], r["affected"]), {}).setdefault(r["policy"], r["sw"])
    keys = sorted(ev)
    x = np.arange(len(keys))
    w = 0.27
    for j, (p, lab, kw) in enumerate([("ESM-norepair", "ESM", dict(color=OI["red"])),
                                      ("TTL25@oracle", "TTL25@oracle", dict(color="#D9D9D9", edgecolor=OI["grey"],
                                                                            hatch="////", lw=0.4)),
                                      ("NEVER", "NEVER", dict(color=OI["blue"]))]):
        a3.bar(x + (j - 1) * w, [100 * ev[k][p] for k in keys], w, label=lab, **kw)
    a3.set_xticks(x)
    a3.set_xticklabels([f"{short[t]} ({n})" for t, n in keys], rotation=40, ha="right", fontsize=5.4)
    a3.set_ylim(0, 118)
    a3.set_yticks([0, 25, 50, 75, 100])
    a3.set_ylabel("served-wrong reads (%)", fontsize=6.2)
    a3.legend(frameon=False, loc="upper center", ncol=3, fontsize=5.6, bbox_to_anchor=(0.5, 1.02))
    a3.set_title("(c) TLC schema events: wrong in next 10 snapshots", loc="left", fontsize=6.8)
    fig.tight_layout(w_pad=1.6)
    save(fig, "fig_lake.pdf")


# ---------------------------------------------------------------- ESWA B3: end-to-end tasks (code + lakes)
# Sources: esm/results/e2e/results.json (generated by esm.e2e.report_e2e) and esm/results/e2e_lake/results.json
# (generated by esm.e2e_lake.report_lake): keys arms[...] (main prompt) and trust[...] ("rely on memory" prompt; the
# NO-MEMORY row of the trust variant is the main run). wrong = [point, lo, hi] (bootstrap over tasks), tok = tokens/task.
def _clust_wrong(d, variant, arm, nb=2000, seed=1):
    """Wrong-action rate with a fact-clustered 95 % bootstrap interval (ESWA round 1: tasks of one fact are not
    independent). Reads the task_outcomes parquet next to the results.json the figure was given."""
    import numpy as np, pandas as pd
    base = os.path.join(ROOT, "esm/results/e2e" if d.get("_kind") == "code" else "esm/results/e2e_lake")
    m = pd.read_parquet(os.path.join(base, "task_outcomes.parquet"))
    df = m if (variant == "main" or arm == "NO-MEMORY") else pd.read_parquet(os.path.join(base, "task_outcomes_trust.parquet"))
    s = df[df.arm == arm]
    if s.empty:
        return None
    x = (s.outcome == "wrong").astype(float).to_numpy()
    g = pd.Series(x).groupby(s.iid.to_numpy())
    S, N = g.sum().to_numpy(), g.size().to_numpy()
    idx = np.random.default_rng(seed).integers(0, len(S), (nb, len(S)))
    lo, hi = np.percentile(S[idx].sum(1) / N[idx].sum(1), [2.5, 97.5])
    return (x.mean(), lo, hi)


def fig_e2e():
    e2e = json.load(open(os.path.join(ROOT, "esm/results/e2e/results.json"), encoding="utf-8"))
    lake = json.load(open(os.path.join(ROOT, "esm/results/e2e_lake/results.json"), encoding="utf-8"))
    e2e["_kind"], lake["_kind"] = "code", "lake"
    fig, axs = plt.subplots(1, 2, figsize=(COL, 2.15))
    specs = [(axs[0], e2e, "TTL100", "(a) Code repositories, 120 tasks", (0, 30), (-0.5, 20)),
             (axs[1], lake, "TTL", "(b) Data lakes, 63 tasks", (0, 85), (-1, 56))]
    style = {"NO-MEMORY": (OI["black"], "o"), "NEVER": (OI["blue"], "o"), "TTL": (OI["green"], "^"),
             "REPLAY": (OI["purple"], "v"), "ESM": (OI["red"], "*"), "ORACLE": (OI["grey"], "s")}
    for ax, d, ttl, title, xl, yl in specs:
        for arm in ["NO-MEMORY", "NEVER", ttl, "REPLAY", "ESM", "ORACLE"]:
            key = "TTL" if arm == ttl else arm
            col, mk = style[key]
            ms = 6.5 if key == "ESM" else 3.6
            m = d["arms"][arm]
            t = d["trust"].get(arm, m) if arm != "NO-MEMORY" else m  # NO-MEMORY has no memory to rely on
            for r, filled, cl in [(m, True, _clust_wrong(d, "main", arm)), (t, False, _clust_wrong(d, "trust", arm))]:
                w, lo, hi = (100 * v for v in (cl if cl is not None else r["wrong"]))
                ax.errorbar(r["tok"] / 1000, w, yerr=[[w - lo], [hi - w]], fmt=mk, ms=ms, color=col, ecolor=col,
                            mfc=col if filled else "white", mec=col, mew=0.7, elinewidth=0.45, capsize=1.0,
                            alpha=1.0 if filled else 0.85, zorder=3 if filled else 2)
            if arm != "NO-MEMORY":
                ax.annotate("", (t["tok"] / 1000, 100 * t["wrong"][0]), (m["tok"] / 1000, 100 * m["wrong"][0]),
                            arrowprops=dict(arrowstyle="->", lw=0.4, color=col, alpha=0.7, shrinkA=2, shrinkB=2))
        ax.axhline(100 * d["arms"]["NO-MEMORY"]["wrong"][0], ls=":", lw=0.6, color=OI["black"], zorder=1)
        ax.set_xlim(*xl)
        ax.set_ylim(*yl)
        ax.set_title(title, loc="left", fontsize=5.9)
        ax.set_xlabel("tokens per task (thousands)", fontsize=6.0)
        ax.grid(True, lw=0.3, alpha=0.5)
    axs[0].set_ylabel("wrong actions (% of tasks)", fontsize=6.2)
    from matplotlib.lines import Line2D
    hs = [Line2D([], [], ls="", marker=style[k][1], color=style[k][0], ms=6 if k == "ESM" else 3.5, label=k)
          for k in ["NO-MEMORY", "NEVER", "TTL", "REPLAY", "ESM", "ORACLE"]]
    hs += [Line2D([], [], ls="", marker="o", color="#555555", ms=3.5, label="main prompt"),
           Line2D([], [], ls="", marker="o", mfc="white", mec="#555555", ms=3.5, label='"rely on memory"')]
    fig.legend(handles=hs, loc="upper center", ncol=4, frameon=False, fontsize=5.3, bbox_to_anchor=(0.53, 1.13),
               handletextpad=0.2, columnspacing=0.8)
    fig.tight_layout(w_pad=0.8)
    save(fig, "fig_e2e.pdf")


# ---------------------------------------------------------------- revision r1 supplementary runs (Figs. S5, S6)
# Source: esm/results/heldout/revision_r1_runs/results.json (generated by revision_r1_runs/analyze.py).
# "H150" keys there are the paper's S160. Estimate C (served-wrong and re-derivation tokens per fact; Table S10 last
# column) comes from esm/results/heldout/revision_r3/estimate_c.json (generated by revision_r3/estimate_c.py; since
# revision r3 it uses the main-run consecutive-pair statistic instead of item6's superseded all-pairs one).
R1RUNS = os.path.join(ROOT, "esm/results/heldout/revision_r1_runs/results.json")
ESTC = os.path.join(ROOT, "esm/results/heldout/revision_r3/estimate_c.json")


def fig_natural():
    """Fig. S5: NAT100 (a) served-wrong vs tokens, (b) token ratio baseline/ESM on NAT100 vs S160."""
    B = json.load(open(R1RUNS, encoding="utf-8"))["B"]
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(FULL, 2.3), gridspec_kw=dict(width_ratios=[1.15, 1]))
    pols = ["NEVER", "TTL100", "CERT-ZS", "CERT-v0", "LLMDIFF", "REPLAY", "ESM-norepair"]
    lab = {"NEVER": "NEVER", "TTL100": "TTL100", "CERT-ZS": "CERT-ZS", "CERT-v0": "CERT-v0h$^{*}$",
           "LLMDIFF": "LLMDIFF", "REPLAY": "REPLAY", "ESM-norepair": "ESM"}
    offs = {"NEVER": (5, 0), "TTL100": (5, 3), "CERT-ZS": (5, -5), "CERT-v0": (4, -9), "LLMDIFF": (5, 4),
            "REPLAY": (5, -4), "ESM-norepair": (-6, 0)}

    def xv(k):
        return max(B[k]["tok"] / 1000.0, 6.0)  # NEVER (0 tokens) drawn at the left edge

    for k in pols:
        r = B[k]
        lo, hi = r["sw_ci"]
        isesm = k == "ESM-norepair"
        a1.errorbar(xv(k), 100 * r["sw"], yerr=[[100 * (r["sw"] - lo)], [100 * (hi - r["sw"])]],
                    fmt="*" if isesm else "o", ms=8 if isesm else 4, color=OI["red"] if isesm else OI["blue"],
                    ecolor=OI["red"] if isesm else OI["blue"], elinewidth=0.6, capsize=1.5)
        dx, dy = offs[k]
        a1.annotate(lab[k], (xv(k), 100 * r["sw"]), xytext=(dx, dy), textcoords="offset points", fontsize=5.8,
                    ha="left" if dx > 0 else "right", va="center", color=OI["red"] if isesm else "black")
    a1.set_xscale("log")
    a1.set_xlim(5, 160)
    a1.set_ylim(0, 22)
    a1.set_xticks([6, 10, 20, 50, 100])
    a1.set_xticklabels(["0", "10", "20", "50", "100"])
    a1.minorticks_off()
    a1.set_xlabel("LLM tokens per fact, 400 commits (thousands, log)")
    a1.set_ylabel("served-wrong reads (%)")
    a1.grid(True, which="major", lw=0.3, alpha=0.5)
    a1.set_title("(a) NAT100: accuracy and cost", loc="left")

    base = ["TTL100", "CERT-ZS", "CERT-v0", "LLMDIFF", "REPLAY"][::-1]
    y = list(range(len(base)))
    for i, k in enumerate(base):
        p = B[f"paired|{k}"]
        lo, hi = p["ratio_clu_ci"]
        a2.errorbar(p["ratio"], i + 0.12, xerr=[[p["ratio"] - lo], [hi - p["ratio"]]], fmt="o", ms=4,
                    color=OI["blue"], ecolor=OI["blue"], elinewidth=0.6, capsize=1.5,
                    label="NAT100 (100 natural facts; repository CI)" if i == 0 else None)
        a2.plot(B[f"h150|{k}"]["ratio"], i - 0.12, "s", ms=3.8, mfc="none", mec=OI["orange"], mew=0.9,
                label="S160 (change-enriched)" if i == 0 else None)
        a2.text(hi * 1.06, i + 0.12, f"{p['ratio']:.2f}", fontsize=5.6, va="center", color=OI["blue"])
    a2.axvline(1.0, color="#333333", lw=0.6, ls="--")
    a2.set_xscale("log")
    a2.set_xlim(0.6, 14)
    a2.set_xticks([1, 2, 4, 8])
    a2.set_xticklabels(["1", "2", "4", "8"])
    a2.minorticks_off()
    a2.set_yticks(y)
    a2.set_yticklabels([lab[k] for k in base])
    a2.set_ylim(-0.6, len(base) + 0.7)
    a2.set_xlabel("LLM tokens, baseline / ESM (log)")
    a2.legend(loc="upper right", frameon=False, handletextpad=0.3, borderaxespad=0.1)
    a2.grid(True, axis="x", which="major", lw=0.3, alpha=0.5)
    a2.set_title("(b) Cost ratio: natural sample vs S160", loc="left")
    fig.tight_layout(w_pad=1.2)
    save(fig, "fig_natural.pdf")


def fig_expiry():
    """Fig. S6: real anchor-expiry run on S160: (a) paired change in served-wrong vs extra tokens,
    (b) frozen-ESM wrong reads fixed and right reads broken by each expiry arm."""
    A = json.load(open(R1RUNS, encoding="utf-8"))["A"]
    rows = A["rows"]
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(FULL, 2.3), gridspec_kw=dict(width_ratios=[1.15, 1]))
    EC = json.load(open(ESTC, encoding="utf-8"))["hybrid"]  # estimate C, re-derivation tokens only (Table S10)
    for N in (200, 100, 50):
        for mode, col, mk, name in (("exp", OI["blue"], "o", "every anchor"),
                                    ("expS", OI["green"], "D", "NONE-suspicious only")):
            r = rows[f"ESM-norepair-{mode}{N}"]
            p = r["paired"]
            lo, hi = p["clu"][0], p["clu"][1]
            a1.errorbar(p["dt"] / 1000, 100 * p["d"], yerr=[[100 * (p["d"] - lo)], [100 * (hi - p["d"])]],
                        fmt=mk, ms=4 if mk == "o" else 3.5, color=col, ecolor=col, elinewidth=0.6, capsize=1.5,
                        label=f"real run, {name}" if N == 200 else None)
            a1.annotate(f"N={N}", (p["dt"] / 1000, 100 * p["d"]), xytext=(4, -7 if mode == "expS" else 6),
                        textcoords="offset points", fontsize=5.4, color=col)
        c = EC[f"H150|{N}|C|all anchors"]
        a1.plot(c["tok_per_fact"] / 1000, 100 * (c["sw"] - c["base_sw"]), "s", ms=3.5, mfc="none", mec=OI["grey"], mew=0.8,
                label="estimate C (Table S10), every anchor" if N == 200 else None)
    a1.axhline(0, color="#333333", lw=0.6, ls="--")
    a1.set_xscale("log")
    a1.set_xlim(0.9, 140)
    a1.set_xticks([1, 2, 5, 10, 20, 50, 100])
    a1.set_xticklabels(["1", "2", "5", "10", "20", "50", "100"])
    a1.minorticks_off()
    a1.set_ylim(-0.95, 2.3)
    a1.set_xlabel("extra LLM tokens per fact vs frozen ESM (thousands, log)")
    a1.set_ylabel("$\\Delta$ served-wrong (pp)")
    a1.legend(loc="upper left", frameon=False, handletextpad=0.3, borderaxespad=0.1)
    a1.grid(True, which="major", lw=0.3, alpha=0.5)
    a1.set_title("(a) Paired change (repository 95 % CI)", loc="left")

    arms = [f"ESM-norepair-exp{N}" for N in (200, 100, 50)] + [f"ESM-norepair-expS{N}" for N in (200, 100, 50)]
    names = ["every\n200", "every\n100", "every\n50", "susp.\n200", "susp.\n100", "susp.\n50"]
    x = list(range(len(arms)))
    w = 0.38
    fix = [rows[a]["removed"] for a in arms]
    brk = [rows[a]["introduced"] for a in arms]
    a2.bar([i - w / 2 for i in x], fix, w, color=OI["green"], label="frozen-ESM wrong reads fixed")
    a2.bar([i + w / 2 for i in x], brk, w, color=OI["red"], label="frozen-ESM right reads broken")
    for i in x:
        a2.text(i - w / 2, fix[i] + 12, f"{fix[i]}", ha="center", fontsize=5.0)
        a2.text(i + w / 2, brk[i] + 12, f"{brk[i]}", ha="center", fontsize=5.0)
    a2.set_xticks(x)
    a2.set_xticklabels(names, fontsize=5.8)
    a2.set_xlabel("expiry applies to, $N$")
    a2.set_ylabel("reads (160 facts $\\times$ 400 commits)")
    a2.set_ylim(0, 1000)
    a2.legend(loc="upper right", frameon=False, handletextpad=0.3, borderaxespad=0.1)
    a2.set_title("(b) Reads changed against the frozen ESM", loc="left")
    fig.tight_layout(w_pad=1.2)
    save(fig, "fig_expiry.pdf")


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:  # e.g. make_figs.py fig_natural fig_expiry
        for name in sys.argv[1:]:
            globals()[name]()
        sys.exit(0)
    fig_method()
    fig_negative()
    fig_pareto_heldout()
    fig_detection()
    fig_schedules()
    fig_stream()
    fig_anchored()
    fig_lake()
    fig_natural()
    fig_expiry()
    fig_e2e()
