"""Dev-set analysis: tables, operating curves, error taxonomy, sanity check.  Zero LLM (reads simulation outputs only).
usage: python -m esm.scripts.report  ->  esm/results/dev/{tables.md, results.json, records.parquet, *.png}"""
import json, glob, os
from collections import Counter, defaultdict
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from esm import metrics as M
from esm.common import DATA, RESULTS
from esm.envs.pyrepo import load_dev_facts

F = load_dev_facts()
FX = {f["iid"]: f for f in F}
SUB = {k: set(json.load(open(DATA / f"sub_{k}.json"))) for k in ("S1", "S3", "SR")}
SUB["ALL"] = set(FX)

# ------------------------------------------------------------------ load
frames, PF = [], {}
for p in sorted(glob.glob(str(DATA / "sim" / "*.parquet"))):
    pol, sch = os.path.basename(p)[:-8].split("__")
    d = pd.read_parquet(p)
    d["policy"], d["schedule"] = pol, sch
    frames.append(d)
    PF[(pol, sch)] = M.per_fact(d, F)
REC = pd.concat(frames, ignore_index=True)
REC.to_parquet(RESULTS / "records.parquet", index=False)

DER = {}
for l in open(DATA / "derivations.jsonl", encoding="utf-8"):
    r = json.loads(l)
    DER.setdefault((r["iid"], r["t"]), r)

OUT = {}
L = []


def pct(x):
    return "–" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{100 * x:.1f}"


def ci(c):
    return f"[{100 * c[0]:.1f}, {100 * c[1]:.1f}]"


def row(name, pf, ids=None):
    if ids is not None:
        pf = pf[pf.index.isin(ids)]
    s = M.summary(pf)
    if s is None:
        return None, None
    rep = f"{s['repairs']} ({pct(s['repair_rate'])} %)" if s["repairs"] else "–"
    return s, (f"| {name} | {s['n']} | {pct(s['ff'])} {ci(s['ff_ci'])} | {pct(s['fs'])} {ci(s['fs_ci'])} | {pct(s['sw'])} {ci(s['sw_ci'])} "
               f"| {s['tok_per_fact'] / 1000:.1f}k | {s['rde_sum']:.2f} | {s['calls_per_fact']:.1f} | {s['der_per_fact']:.2f} "
               f"| {pct(s['needless_frac'])} | {rep} | {pct(s['ever_sw_chg'])} | {pct(s['eps_missed'])} |")


HDR = ("| policy | facts | FF % [CI] | FS % [CI] | served-wrong % [CI] | tokens/fact | RDE | eval calls/fact | re-derivations/fact "
       "| needless spend % | repairs (correct) | changing facts ever served wrong % | stored-wrong episodes never acted on % |\n"
       "|---|---|---|---|---|---|---|---|---|---|---|---|---|")


def table(title, policies, ids, sch="every", note=""):
    L.append(f"\n### {title}\n")
    if note:
        L.append(note + "\n")
    L.append(HDR)
    res = {}
    for name in policies:
        if (name, sch) not in PF:
            continue
        pf = PF[(name, sch)]
        have = set(pf.index)
        idx = ids & have
        if len(idx) < len(ids):
            name_ = f"{name} (only {len(idx)}/{len(ids)})"
        else:
            name_ = name
        s, line = row(name_, pf, idx)
        if line:
            L.append(line)
            res[name] = s
    return res


ESMV = ["ESM", "ESM-noanchor", "ESM-trunc", "ESM-noanchor-trunc", "ESM-norepair", "ESM-unsurefresh", "ESM-chain",
        "ESM-9B", "ESM-n3", "ESM-n3maj", "ESM-n3-unsurefresh", "ESM@oracle"]
BASE = ["NEVER", "ALWAYS", "TTL50", "TTL100", "TTL200", "REPLAY", "FILEHASH", "ASTHASH", "CITE", "CERT-ZS", "CERT-v0", "LLMDIFF"]
BASEO = [b + "@oracle" for b in BASE if b not in ("NEVER",)]

L.append("# ESM v1 dev-set tables (generated by esm/scripts/report.py)\n")
L.append("FF/FS/served-wrong are pooled over (fact, read) pairs; CIs: bootstrap over facts (B = 1000). RDE = total tokens / "
         "logged s0 derivation tokens (sum over facts / sum over facts). '@oracle' = re-derivation replaced by the oracle "
         "answer (idealised; logged-derivation token cost).")
OUT["main_all"] = table("T1a. All 285 facts, read at every commit", ["ESM", "ESM-noanchor-trunc", "NEVER"] + BASEO + ["ESM@oracle"], SUB["ALL"])
OUT["main_S1"] = table("T1b. Ablations on S1 (86 facts, pilot7's stratified 30 % subsample), every commit", ESMV + ["NEVER"], SUB["S1"])
OUT["main_SR"] = table("T1c. Real re-derivation baselines on SR (40 facts), every commit", ["ESM", "ESM-noanchor-trunc"] + BASE + BASEO, SUB["SR"])

# ------------------------------------------------------------------ paired
L.append("\n### T2. Paired differences A − B (pp; tokens per fact), bootstrap over common facts (B = 2000)\n")
L.append("| A − B | set | facts | ΔFF [CI] | ΔFS [CI] | Δserved-wrong [CI] | Δtokens/fact [CI] |\n|---|---|---|---|---|---|---|")
PAIRS = [("ESM", "ESM-noanchor-trunc", "ALL")] + [("ESM", x, "S1") for x in ESMV[1:] if x != "ESM@oracle"] + \
        [("ESM", b, "SR") for b in BASE] + [("ESM", b, "ALL") for b in BASEO] + [("ESM", "NEVER", "ALL")]
OUT["paired"] = {}
for a_, b_, s_ in PAIRS:
    if (a_, "every") not in PF or (b_, "every") not in PF:
        continue
    pa, pb = PF[(a_, "every")], PF[(b_, "every")]
    ids = SUB[s_] & set(pa.index) & set(pb.index)
    if len(ids) < 5:
        continue
    r = M.paired(pa.loc[sorted(ids)], pb.loc[sorted(ids)])
    OUT["paired"][f"{a_}-{b_}|{s_}"] = r
    L.append(f"| {a_} − {b_} | {s_} | {r['n']} | {100 * r['dff']:+.1f} [{100 * r['dff_ci'][0]:+.1f}, {100 * r['dff_ci'][1]:+.1f}] "
             f"| {100 * r['dfs']:+.1f} [{100 * r['dfs_ci'][0]:+.1f}, {100 * r['dfs_ci'][1]:+.1f}] "
             f"| {100 * r['dsw']:+.1f} [{100 * r['dsw_ci'][0]:+.1f}, {100 * r['dsw_ci'][1]:+.1f}] "
             f"| {r['dtok'] / 1000:+.1f}k [{r['dtok_ci'][0] / 1000:+.1f}, {r['dtok_ci'][1] / 1000:+.1f}] |")

# ------------------------------------------------------------------ splits
L.append("\n### T3. ESM (every commit) split by slice / type / repo\n")
L.append("| split | facts | FF % | FS % | served-wrong % | tokens/fact | RDE | repairs (correct) |\n|---|---|---|---|---|---|---|---|")
if ("ESM", "every") in PF:
    pf = PF[("ESM", "every")]
    for col in ("slice", "type", "repo"):
        for v, sub in pf.groupby(col):
            s = M.summary(sub)
            L.append(f"| {col}={v} | {s['n']} | {pct(s['ff'])} | {pct(s['fs'])} | {pct(s['sw'])} | {s['tok_per_fact'] / 1000:.1f}k | {s['rde_sum']:.2f} "
                     f"| {s['repairs']} ({pct(s['repair_rate'])}) |")

# ------------------------------------------------------------------ schedules
L.append("\n### T4. Read schedules (cost per read)\n")
L.append("| policy | schedule | facts | reads/fact | served-wrong % | FF % | FS % | tokens/fact | tokens/read | eval calls/fact | re-derivations/fact |\n|---|---|---|---|---|---|---|---|---|---|---|")
OUT["sched"] = {}
for (pol, sch), pf in sorted(PF.items()):
    if pol.startswith("DETECT"):
        continue
    s = M.summary(pf)
    OUT["sched"][f"{pol}|{sch}"] = s
    L.append(f"| {pol} | {sch} | {s['n']} | {s['reads'] / s['n']:.0f} | {pct(s['sw'])} | {pct(s['ff'])} | {pct(s['fs'])} | {s['tok_per_fact'] / 1000:.1f}k "
             f"| {s['tok_per_read']:.0f} | {s['calls_per_fact']:.1f} | {s['der_per_fact']:.2f} |")

# ------------------------------------------------------------------ detection-only (pilot7 framework)
L.append("\n### T5. Detection only, pilot7 framework (stored answer always the s0 K; FF/FS per commit as in pilot7)\n")
L.append("| detector | facts | FF % [CI] | FS % [CI] | static FF/FS | behaviour FF/FS | calls/fact |\n|---|---|---|---|---|---|---|")
OUT["detect"] = {}
for pol in ["DETECT-p7a", "DETECT-p7b", "DETECT-anchor-hier", "DETECT-anchor-trunc", "DETECT-noanchor-hier", "DETECT-9B", "DETECT-n3"]:
    if (pol, "every") not in PF:
        continue
    pf = PF[(pol, "every")]
    for sname in ("ALL", "S1"):
        ids = SUB[sname] & set(pf.index)
        if sname == "S1" and len(ids) == len(pf):
            continue
        sub = pf.loc[sorted(ids)]
        s = M.summary(sub)
        st, bh = M.summary(sub[sub.slice == "static"]), M.summary(sub[sub.slice == "behav"])
        OUT["detect"][f"{pol}|{sname}"] = {"all": s, "static": st, "behav": bh}
        L.append(f"| {pol} ({sname}) | {s['n']} | {pct(s['ff'])} {ci(s['ff_ci'])} | {pct(s['fs'])} {ci(s['fs_ci'])} "
                 f"| {pct(st['ff']) if st else '–'} / {pct(st['fs']) if st else '–'} | {pct(bh['ff']) if bh else '–'} / {pct(bh['fs']) if bh else '–'} "
                 f"| {s['calls_per_fact']:.1f} |")

# ------------------------------------------------------------------ re-derivation accuracy
L.append("\n### T6. Re-derivation (qwen3.5:9b agent) accuracy\n")
dd = pd.DataFrame([{"iid": k[0], "t": k[1], "correct": r["correct"], "tok": sum(r["tokens"]), "n_new": r.get("n_new", 0),
                    "slice": FX[k[0]]["slice"], "answered": r["answer"] is not None} for k, r in DER.items() if k[0] in FX])
OUT["derivations"] = {}
if len(dd):
    L.append("| subset | derivations | facts | correct % | answered % | tokens/derivation (mean) |\n|---|---|---|---|---|---|")
    for name, sub in [("all", dd), ("static", dd[dd.slice == "static"]), ("behav", dd[dd.slice == "behav"]), ("t = 0 (s0)", dd[dd.t == 0]),
                      ("grid t in 50..400 (SR)", dd[(dd.t % 50 == 0) & (dd.t > 0) & dd.iid.isin(SUB["SR"])])]:
        if len(sub):
            OUT["derivations"][name] = {"n": len(sub), "acc": float(sub.correct.mean()), "tok": float(sub.tok.mean())}
            L.append(f"| {name} | {len(sub)} | {sub.iid.nunique()} | {pct(sub.correct.mean())} | {pct(sub.answered.mean())} | {sub.tok.mean() / 1000:.1f}k |")
    logged = np.mean([sum(f["derive_tokens"]) for f in F])
    L.append(f"\nLogged s0 derivations (the RDE unit): mean {logged / 1000:.1f}k tokens per fact.")

# ------------------------------------------------------------------ error taxonomy (ESM, every)
def taxonomy(pol="ESM", sch="every"):
    d = REC[(REC.policy == pol) & (REC.schedule == sch)].sort_values(["iid", "t"])
    cats = Counter()
    fcats = defaultdict(set)
    ex = defaultdict(list)
    for iid, x in d.groupby("iid"):
        origin, origin_ok = "s0", True
        for r in x.itertuples():
            if r.action in ("repair", "rederive"):
                origin, origin_ok = r.action, bool(r.served_valid)
            if r.served_valid:
                continue
            if not origin_ok and r.action not in ("repair", "rederive"):
                c = f"persisting wrong {origin}"
            elif r.action == "repair":
                c = "wrong in-place repair (judge's new_answer wrong)"
            elif r.action == "rederive":
                c = "wrong re-derivation (agent answer wrong)"
            elif r.action == "same":
                c = "missed: evidence state unchanged (change outside the recorded evidence)"
            elif r.action == "memo":
                c = "missed: memoised still_valid reused on a state whose truth differs"
            elif r.action in ("valid", "unsure_fresh"):
                c = f"missed: judge said {r.verdict} on a changed state"
            else:
                c = r.action
            cats[c] += 1
            fcats[c].add(iid)
            if len(ex[c]) < 4 and (not ex[c] or ex[c][-1][0] != iid):
                ex[c].append((iid, int(r.t), FX[iid]["K"][:40], str(r.served)[:40], FX[iid]["truth"][300 + int(r.t)][:40]))
    return cats, fcats, ex


L.append("\n### T7. Error taxonomy of ESM's wrong-served reads (all facts, every commit)\n")
if ("ESM", "every") in PF:
    cats, fcats, ex = taxonomy()
    tot = sum(cats.values())
    OUT["taxonomy"] = {k: {"reads": v, "facts": len(fcats[k])} for k, v in cats.items()}
    L.append(f"Total wrong-served reads: {tot} of {len(REC[(REC.policy == 'ESM') & (REC.schedule == 'every')])}.\n")
    L.append("| cause | reads | % of wrong reads | facts | examples (fact, t, K, served, truth) |\n|---|---|---|---|---|")
    for k, v in cats.most_common():
        exs = "; ".join(f"`{a}` t={b}: K={c!r} served={d!r} truth={e!r}" for a, b, c, d, e in ex[k][:2])
        L.append(f"| {k} | {v} | {100 * v / max(tot, 1):.1f} | {len(fcats[k])} | {exs} |")

# ------------------------------------------------------------------ curves
def curve_points(ids_name):
    pts = []
    for (pol, sch), pf in PF.items():
        if sch != "every" or pol.startswith("DETECT"):
            continue
        ids = SUB[ids_name] & set(pf.index)
        if len(ids) < len(SUB[ids_name]):
            continue
        s = M.summary(pf.loc[sorted(ids)])
        pts.append((pol, s))
    return pts


OUT["curves"] = {}
for ids_name in ("ALL", "S1", "SR"):
    pts = curve_points(ids_name)
    if len(pts) < 2:
        continue
    OUT["curves"][ids_name] = {p: {k: s[k] for k in ("ff", "fs", "sw", "tok_per_fact", "rde_sum")} for p, s in pts}
    fig, ax = plt.subplots(1, 2, figsize=(13, 5.2))
    for pol, s in pts:
        c = "C3" if pol.startswith("ESM") else ("C7" if "@oracle" in pol else "C0")
        ax[0].scatter(100 * s["ff"], 100 * s["fs"], color=c, s=25)
        ax[0].annotate(pol, (100 * s["ff"], 100 * s["fs"]), fontsize=7)
        ax[1].scatter(max(s["rde_sum"], 1e-3), 100 * s["sw"], color=c, s=25)
        ax[1].annotate(pol, (max(s["rde_sum"], 1e-3), 100 * s["sw"]), fontsize=7)
    # Pareto frontier (cost, served-wrong) over non-oracle policies
    real = sorted([(s["rde_sum"], 100 * s["sw"], p) for p, s in pts if "@oracle" not in p])
    fr, best = [], 1e9
    for x, y, p in real:
        if y < best:
            fr.append((max(x, 1e-3), y)); best = y
    if fr:
        ax[1].step([a for a, _ in fr], [b for _, b in fr], where="post", color="k", lw=0.8, alpha=0.6)
    ax[0].set_xlabel("FF % (stored answer wrong, served)"); ax[0].set_ylabel("FS % (stored answer right, maintained)")
    ax[1].set_xscale("log"); ax[1].set_xlabel("cost: re-derivation-equivalents per fact (log)"); ax[1].set_ylabel("served-wrong % of reads")
    ax[0].set_title(f"FF–FS ({ids_name}, every commit)"); ax[1].set_title(f"accuracy vs cost ({ids_name}); red = ESM variants, grey = @oracle")
    fig.tight_layout()
    fig.savefig(RESULTS / f"curves_{ids_name}.png", dpi=130)
    plt.close(fig)

(RESULTS / "tables.md").write_text("\n".join(L), encoding="utf-8")
(RESULTS / "results.json").write_text(json.dumps(OUT, indent=1, default=float), encoding="utf-8")
print("written", RESULTS / "tables.md")
