"""Held-out analysis (zero LLM): tables, curves, taxonomy, dev calibration.
usage: ESM_DATA=<E:...esm_data_heldout> ESM_STAGE=heldout python -m esm.scripts.report_heldout
-> esm/results/heldout/{tables.md, results.json, records.parquet, curves_*.png}"""
import json, glob, os
from collections import Counter, defaultdict
os.environ["ESM_LLM_OFFLINE"] = "1"
os.environ.setdefault("ESM_STAGE", "heldout")
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from esm import metrics as M
from esm.common import DATA, DEV_DATA, RESULTS
from esm.policies import Context

ctx = Context.load("heldout")
F = ctx.facts
FX = {f["iid"]: f for f in F}
RAW = ctx.raw
SUB = {"ALL": set(FX)}
for k in ("H150", "H80R"):
    p = DATA / f"sub_{k}.json"
    if p.exists():
        SUB[k] = set(json.loads(p.read_text())) & set(FX)
L, OUT = [], {}


def pct(x):
    return "–" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{100 * x:.1f}"


def ci(c):
    return f"[{100 * c[0]:.1f}, {100 * c[1]:.1f}]"


# ------------------------------------------------------------------ load simulations
frames, PF = [], {}
for p in sorted(glob.glob(str(DATA / "sim" / "*.parquet"))):
    pol, sch = os.path.basename(p)[:-8].split("__")
    d = pd.read_parquet(p)
    d = d[d.iid.isin(FX)]
    if not len(d):
        continue
    d["policy"], d["schedule"] = pol, sch
    frames.append(d)
    PF[(pol, sch)] = M.per_fact(d, F)
REC = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
if len(REC):
    REC.to_parquet(RESULTS / "records.parquet", index=False)

# one-time certificate construction cost (added to CERT-ZS / CERT-v0 rows as setup tokens)
SETUP = {}
for f in F:
    ct = f.get("cert_tokens") or {}
    SETUP[("CERT-ZS", f["iid"])] = ct.get("certzs") or 0
    SETUP[("CERT-v0", f["iid"])] = ct.get("certv0h") or 0


def with_setup(pol, pf):
    base = pol.split("@")[0]
    if base in ("CERT-ZS", "CERT-v0") and "@oracle" not in pol:
        pf = pf.copy()
        add = np.array([SETUP.get((base, i), 0) for i in pf.index], float)
        pf["tok"] = pf.tok + add
        pf["rde"] = pf.tok / pf.dtok
    return pf


def summ(pf, ids=None):
    if ids is not None:
        pf = pf[pf.index.isin(ids)]
    if not len(pf):
        return None
    return M.summary(pf)


def repo_weighted(pf, ids=None, seed=0, nb=1000):
    """served-wrong averaged over repos with equal weight (bootstrap: facts resampled within repo)."""
    if ids is not None:
        pf = pf[pf.index.isin(ids)]
    groups = [g for _, g in pf.groupby("repo")]
    est = np.mean([g.sw.sum() / g.reads.sum() for g in groups])
    rng = np.random.default_rng(seed)
    bs = []
    arrs = [(g.sw.to_numpy(float), g.reads.to_numpy(float)) for g in groups]
    for _ in range(nb):
        v = []
        for sw, rd in arrs:
            ix = rng.integers(0, len(sw), len(sw))
            v.append(sw[ix].sum() / rd[ix].sum())
        bs.append(np.mean(v))
    return est, np.percentile(bs, [2.5, 97.5]).tolist()


HDR = ("| policy | facts | served-wrong % [CI] | FF % | FS % | episodes never acted on % | lifetime kept % | tokens/fact | tokens/read "
       "| RDE | judge calls/fact | re-derivations/fact | repairs (correct) | changing facts ever served wrong % |\n"
       "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")


def line(name, s):
    rep = f"{s['repairs']} ({pct(s['repair_rate'])} %)" if s["repairs"] else "–"
    return (f"| {name} | {s['n']} | {pct(s['sw'])} {ci(s['sw_ci'])} | {pct(s['ff'])} | {pct(s['fs'])} | {pct(s['eps_missed'])} "
            f"| {pct(s['life_kept'])} | {s['tok_per_fact'] / 1000:.1f}k | {s['tok_per_read']:.0f} | {s['rde_sum']:.2f} | {s['calls_per_fact']:.1f} "
            f"| {s['der_per_fact']:.2f} | {rep} | {pct(s['ever_sw_chg'])} |")


def table(title, policies, ids, sch="every", note="", key=None, require_full=False):
    L.append(f"\n### {title}\n")
    if note:
        L.append(note + "\n")
    L.append(HDR)
    res = {}
    for name in policies:
        if (name, sch) not in PF:
            continue
        pf = with_setup(name, PF[(name, sch)])
        idx = ids & set(pf.index)
        if not idx or (require_full and len(idx) < len(ids)):
            continue
        s = summ(pf, idx)
        lab = name if len(idx) == len(ids) else f"{name} (only {len(idx)}/{len(ids)})"
        L.append(line(lab, s))
        res[name] = s
    if key:
        OUT[key] = res
    return res


# ------------------------------------------------------------------ T0: s0 derivation success
L.append("# ESM held-out tables (generated by esm/scripts/report_heldout.py)\n")
L.append("All rates are pooled over (fact, read) pairs unless stated. CIs: bootstrap over facts (B = 1000). RDE = tokens / the fact's "
         "own s0 derivation tokens (27B agent), sum over facts / sum over facts. '@oracle' = re-derivation replaced by the oracle "
         "answer (idealised reference; cost = the s0 derivation's tokens). tokens/read = total evaluator + re-derivation tokens / reads.")
L.append("\n### T0. s0 derivation (qwen3.6:27b agent, ≤ 12 tool calls) — a fact is kept iff its answer matches the oracle at s0\n")
raw = pd.DataFrame([{"iid": f["iid"], "repo": f["repo"], "type": f["type"], "slice": f["slice"], "subset": f["subset"],
                     "status": f.get("s0_status", "missing"),
                     "tok": sum((f.get("s0") or {}).get("tokens") or [0, 0]), "calls": (f.get("s0") or {}).get("n_llm", 0),
                     "ntool": len((f.get("s0") or {}).get("trace") or [])} for f in RAW])
OUT["s0"] = {}
L.append("| split | facts | derived | correct % | wrong % | no answer % | tokens/derivation | LLM calls | tool calls |\n|---|---|---|---|---|---|---|---|---|")
for col in (None, "slice", "subset", "type", "repo"):
    groups = [("all", raw)] if col is None else [(f"{col}={v}", g) for v, g in raw.groupby(col)]
    for name, g in groups:
        d = g[g.status != "missing"]
        if not len(d):
            continue
        r = {"n": len(g), "derived": len(d), "correct": float((d.status == "correct").mean()), "wrong": float((d.status == "wrong").mean()),
             "noans": float((d.status == "no_answer").mean())}
        OUT["s0"][name] = r
        L.append(f"| {name} | {len(g)} | {len(d)} | {pct(r['correct'])} | {pct(r['wrong'])} | {pct(r['noans'])} | {d.tok.mean() / 1000:.1f}k "
                 f"| {d.calls.mean():.1f} | {d.ntool.mean():.1f} |")
kept = pd.DataFrame([{"iid": f["iid"], "repo": f["repo"], "slice": f["slice"], "subset": f["subset"], "type": f["type"],
                      "changing": not all(f["valid"]), "n_inv": sum(not v for v in f["valid"])} for f in F])
L.append(f"\nKept facts: {len(F)} (changing in FUTURE w.r.t. the stored answer: {int(kept.changing.sum())}; "
         f"invalid (fact, commit) pairs: {100 * kept.n_inv.sum() / (400 * len(kept)):.1f} %). "
         + ", ".join(f"{k}: {int(v)}" for k, v in kept.groupby("subset").size().items()) + "; "
         + ", ".join(f"{k}: {int(v)}" for k, v in kept.groupby("slice").size().items()) + ".")
if "H150" in SUB:
    h = kept[kept.iid.isin(SUB["H150"])]
    L.append(f"H150: {len(h)} facts ({int(h.changing.sum())} changing; " + ", ".join(f"{k}: {int(v)}" for k, v in h.groupby("subset").size().items())
             + "; " + ", ".join(f"{k}: {int(v)}" for k, v in h.groupby("slice").size().items()) + ").")

# ------------------------------------------------------------------ main tables
ESMV = ["ESM", "ESM-verify", "ESM-norepair", "ESM-noanchor", "ESM-verify-noanchor", "ESM-trunc", "ESM-verify-trunc", "ESM-unsurefresh",
        "ESM-verify-unsurefresh", "ESM-n2", "ESM-verify-n2", "ESM-9B", "ESM-verify-9B", "ESM-9Bderiver", "ESM-verify-9Bderiver",
        "ESM-noanchor-trunc", "ESM-norepair-noanchor", "ESM-norepair-trunc", "ESM-norepair-noanchor-trunc", "ESM-norepair-unsurefresh",
        "ESM-norepair-9B", "ESM-norepair-9Bderiver", "ESM-norepair-n2"]
BASE = ["NEVER", "ALWAYS", "TTL50", "TTL100", "TTL200", "REPLAY", "FILEHASH", "ASTHASH", "CITE", "CERT-ZS", "CERT-v0", "LLMDIFF"]
BASEO = [b + "@oracle" for b in BASE if b != "NEVER"]
FROZEN = json.loads((DATA / "frozen.json").read_text())["policy"] if (DATA / "frozen.json").exists() else "ESM"
OUT["frozen"] = FROZEN
NAT = {i for i in SUB["ALL"] if FX[i]["subset"] == "natural"}
ENR = SUB["ALL"] - NAT
BEH = {i for i in SUB["ALL"] if FX[i]["slice"] == "behav"}
STA = SUB["ALL"] - BEH
NOJ = {i for i in SUB["ALL"] if FX[i]["repo"] != "jinja"}
note = f"Frozen ESM configuration (chosen on the dev set, T8): **{FROZEN}**."
for nm, ids in (("ALL", SUB["ALL"]), ("natural subset", NAT), ("enriched subset", ENR), ("behaviour slice", BEH), ("static slice", STA),
                ("without jinja", NOJ)):
    table(f"T1 [{nm}] read at every commit ({len(ids)} facts)", [FROZEN, "NEVER"] + [p for p in BASEO] + [FROZEN + "@oracle"], ids,
          note=note if nm == "ALL" else "", key=f"T1|{nm}")
# repo-weighted
L.append("\n### T1-rw. Repo-weighted served-wrong % (each repo weight 1/16; CI: facts resampled within repo), every commit\n")
L.append("| policy | ALL | natural | behaviour | without jinja |\n|---|---|---|---|---|")
OUT["T1rw"] = {}
for name in [FROZEN, "NEVER"] + BASEO:
    if (name, "every") not in PF:
        continue
    pf = PF[(name, "every")]
    cells, o = [], {}
    for nm, ids in (("ALL", SUB["ALL"]), ("natural", NAT), ("behaviour", BEH), ("nojinja", NOJ)):
        idx = ids & set(pf.index)
        if len(idx) < len(ids):
            cells.append("–")
            continue
        e, c = repo_weighted(pf, idx)
        o[nm] = (e, c)
        cells.append(f"{pct(e)} {ci(c)}")
    OUT["T1rw"][name] = o
    L.append(f"| {name} | " + " | ".join(cells) + " |")

if "H150" in SUB:
    H = SUB["H150"]
    table(f"T1c. H150 ({len(H)} facts): real 27B re-derivation baselines vs ESM, every commit (ALWAYS: reads every 50)",
          [FROZEN] + [v for v in ESMV if v != FROZEN] + BASE + BASEO + [FROZEN + "@oracle"], H, key="T1c")
    for sch in ("every20", "every50"):
        table(f"T1d. H150, schedule {sch} (real re-derivations)", [FROZEN] + BASE + BASEO, H, sch=sch, key=f"T1d|{sch}")

if "H80R" in SUB:
    table(f"T1e. H80R ({len(SUB['H80R'])} facts, seeded random half of H150): REPLAY with real re-derivation at every commit",
          [FROZEN, "REPLAY", "CERT-ZS", "TTL50", "TTL100", "ESM-verify", "NEVER", "REPLAY@oracle"], SUB["H80R"], key="T1e")

# ------------------------------------------------------------------ sensitivity: reads whose oracle value is NONE excluded
L.append("\n### T1-nn. Sensitivity: served-wrong % over reads whose oracle value is NOT 'NONE' (referent present), every commit\n")
L.append("The oracle answers NONE when the referent is gone, including when a question's pinned file path moved (e.g. jinja's "
         "move to src/) and at transient breakages (a commit whose file does not parse). Agents often answer the moved/broken "
         "referent with a value; this table removes those reads from both numerator and denominator.\n")
L.append("| policy | set | facts | reads kept % | served-wrong % (all reads) | served-wrong % (truth ≠ NONE) |\n|---|---|---|---|---|---|")
OUT["T1nn"] = {}
NONEMASK = {i: np.array([FX[i]["truth"][300 + t] == "NONE" for t in range(401)]) for i in FX}
for sname in ("ALL", "H150"):
    if sname not in SUB or not len(REC):
        continue
    for pol in [FROZEN, "NEVER", "ESM-norepair-9B", "ESM-norepair-9Bderiver", "CERT-ZS", "TTL100", "TTL200", "TTL50", "LLMDIFF",
                "ESM", "ESM-verify", "ESM-norepair-noanchor", "ESM-norepair-trunc", "ESM-norepair-unsurefresh",
                "REPLAY", "ESM-norepair-n2", "ESM-norepair@oracle",
                "REPLAY@oracle", "TTL100@oracle", "CERT-ZS@oracle", "CITE@oracle"]:
        d = REC[(REC.policy == pol) & (REC.schedule == "every")]
        d = d[d.iid.isin(SUB[sname])]
        if not len(d) or d.iid.nunique() < len(SUB[sname]):
            continue
        nn = ~np.array([NONEMASK[i][t] for i, t in zip(d.iid, d.t)])
        a, b = float((~d.served_valid).mean()), float((~d.served_valid[nn]).mean())
        OUT["T1nn"][f"{pol}|{sname}"] = {"all": a, "nonnone": b, "kept": float(nn.mean())}
        L.append(f"| {pol} | {sname} | {d.iid.nunique()} | {pct(nn.mean())} | {pct(a)} | {pct(b)} |")

# ------------------------------------------------------------------ paired
L.append("\n### T2. Paired differences A − B (pp; tokens per fact), bootstrap over common facts (B = 2000)\n")
L.append("| A − B | set | schedule | facts | Δserved-wrong [CI] | ΔFF [CI] | ΔFS [CI] | Δtokens/fact [CI] |\n|---|---|---|---|---|---|---|---|")
OUT["paired"] = {}
PAIRS = [(FROZEN, "NEVER", "ALL", "every")] + [(FROZEN, b, "ALL", "every") for b in BASEO] + \
        [(FROZEN, b, "H150", "every") for b in BASE + [v for v in ESMV if v != FROZEN]] + \
        [(FROZEN, b, "H150", "every20") for b in BASE] + [(FROZEN, b, "H150", "every50") for b in BASE] +         [(FROZEN, b + "@oracle", "H150", "every") for b in ("REPLAY", "TTL50", "TTL100", "FILEHASH", "CITE")] +         [(FROZEN, "NEVER", "H150", s_) for s_ in ("every5", "bursty", "every50")] + [(FROZEN, "NEVER", "natural", "every"), (FROZEN, "NEVER", "behaviour", "every")] +         [(FROZEN, b, "H80R", "every") for b in ("REPLAY", "CERT-ZS", "TTL50")]
SETS = dict(SUB, natural=NAT, behaviour=BEH)
for a_, b_, s_, sch in PAIRS:
    if (a_, sch) not in PF or (b_, sch) not in PF or s_ not in SETS:
        continue
    pa, pb = with_setup(a_, PF[(a_, sch)]), with_setup(b_, PF[(b_, sch)])
    ids = SETS[s_] & set(pa.index) & set(pb.index)
    if len(ids) < 5:
        continue
    r = M.paired(pa.loc[sorted(ids)], pb.loc[sorted(ids)])
    OUT["paired"][f"{a_}-{b_}|{s_}|{sch}"] = r
    L.append(f"| {a_} − {b_} | {s_} | {sch} | {r['n']} | {100 * r['dsw']:+.1f} [{100 * r['dsw_ci'][0]:+.1f}, {100 * r['dsw_ci'][1]:+.1f}] "
             f"| {100 * r['dff']:+.1f} [{100 * r['dff_ci'][0]:+.1f}, {100 * r['dff_ci'][1]:+.1f}] "
             f"| {100 * r['dfs']:+.1f} [{100 * r['dfs_ci'][0]:+.1f}, {100 * r['dfs_ci'][1]:+.1f}] "
             f"| {r['dtok'] / 1000:+.1f}k [{r['dtok_ci'][0] / 1000:+.1f}, {r['dtok_ci'][1] / 1000:+.1f}] |")

# ------------------------------------------------------------------ splits
L.append(f"\n### T3. {FROZEN} (every commit, ALL) split by slice / subset / type / repo\n")
L.append("| split | facts | changing | served-wrong % [CI] | NEVER served-wrong % | FF % | FS % | episodes never acted on % | tokens/fact | RDE | re-derivations/fact | repairs (correct) |\n|---|---|---|---|---|---|---|---|---|---|---|---|")
OUT["T3"] = {}
if (FROZEN, "every") in PF:
    pf = PF[(FROZEN, "every")]
    pn = PF.get(("NEVER", "every"))
    pf = pf.join(pd.Series({i: FX[i]["subset"] for i in pf.index}, name="subset"))
    for col in ("slice", "subset", "type", "repo"):
        for v, sub in pf.groupby(col):
            s = M.summary(sub)
            sn = M.summary(pn.loc[sub.index]) if pn is not None else None
            OUT["T3"][f"{col}={v}"] = {"esm": s, "never": sn}
            L.append(f"| {col}={v} | {s['n']} | {s['n_chg']} | {pct(s['sw'])} {ci(s['sw_ci'])} | {pct(sn['sw']) if sn else '–'} | {pct(s['ff'])} | {pct(s['fs'])} "
                     f"| {pct(s['eps_missed'])} | {s['tok_per_fact'] / 1000:.1f}k | {s['rde_sum']:.2f} | {s['der_per_fact']:.2f} | {s['repairs']} ({pct(s['repair_rate'])}) |")

# ------------------------------------------------------------------ schedules
L.append("\n### T4. Read schedules (cost per read = total evaluator + re-derivation tokens / reads)\n")
L.append("| policy | schedule | set | facts | reads/fact | served-wrong % [CI] | FF % | FS % | tokens/fact | tokens/read | judge calls/fact | re-derivations/fact |\n|---|---|---|---|---|---|---|---|---|---|---|---|")
OUT["T4"] = {}
for (pol, sch), pf in sorted(PF.items()):
    if pol.startswith("DETECT"):
        continue
    for sname in ("ALL", "H150"):
        if sname not in SUB:
            continue
        ids = SUB[sname] & set(pf.index)
        if len(ids) < len(SUB[sname]) or (sname == "H150" and len(pf) == len(SUB["ALL"])):
            continue
        s = summ(with_setup(pol, pf), ids)
        OUT["T4"][f"{pol}|{sch}|{sname}"] = s
        L.append(f"| {pol} | {sch} | {sname} | {s['n']} | {s['reads'] / s['n']:.0f} | {pct(s['sw'])} {ci(s['sw_ci'])} | {pct(s['ff'])} | {pct(s['fs'])} "
                 f"| {s['tok_per_fact'] / 1000:.1f}k | {s['tok_per_read']:.0f} | {s['calls_per_fact']:.1f} | {s['der_per_fact']:.2f} |")

# ------------------------------------------------------------------ detection only
L.append("\n### T5. Detection only, pilot7 framework (stored answer always the s0 K; FF/FS per commit as in pilot7)\n")
L.append("| detector | set | facts | FF % [CI] | FS % [CI] | static FF / FS | behaviour FF / FS | natural FF / FS | judge calls/fact | tokens/fact |\n|---|---|---|---|---|---|---|---|---|---|")
OUT["T5"] = {}
for pol in ["DETECT-anchor-hier", "DETECT-p7a", "DETECT-anchor-trunc", "DETECT-noanchor-hier", "DETECT-9B", "DETECT-n3"]:
    if (pol, "every") not in PF:
        continue
    pf = PF[(pol, "every")]
    for sname in ("ALL", "H150"):
        if sname not in SUB:
            continue
        ids = SUB[sname] & set(pf.index)
        if not ids or (sname == "ALL" and len(ids) < len(SUB["ALL"])):
            continue
        sub = pf.loc[sorted(ids)]
        s = M.summary(sub)
        st, bh = M.summary(sub[sub.slice == "static"]), M.summary(sub[sub.slice == "behav"])
        na = M.summary(sub[[FX[i]["subset"] == "natural" for i in sub.index]])
        OUT["T5"][f"{pol}|{sname}"] = {"all": s, "static": st, "behav": bh, "natural": na}
        L.append(f"| {pol} | {sname} | {s['n']} | {pct(s['ff'])} {ci(s['ff_ci'])} | {pct(s['fs'])} {ci(s['fs_ci'])} "
                 f"| {pct(st['ff']) if st else '–'} / {pct(st['fs']) if st else '–'} | {pct(bh['ff']) if bh else '–'} / {pct(bh['fs']) if bh else '–'} "
                 f"| {pct(na['ff']) if na else '–'} / {pct(na['fs']) if na else '–'} | {s['calls_per_fact']:.1f} | {s['tok_per_fact'] / 1000:.1f}k |")

# ------------------------------------------------------------------ re-derivation accuracy
L.append("\n### T6. Re-derivation accuracy over time (27B agent; 9B agent where run)\n")
OUT["T6"] = {}
from esm.maintain import read_shards
for model, path in (("27B", DATA / "derivations.jsonl"), ("9B", DATA / "derivations_9b.jsonl")):
    rows = []
    for r in read_shards(path):
        if r["iid"] in FX:
            rows.append({"iid": r["iid"], "t": r["t"], "correct": r["correct"], "tok": sum(r["tokens"]), "answered": r["answer"] is not None,
                         "slice": FX[r["iid"]]["slice"], "subset": FX[r["iid"]]["subset"],
                         "changed": FX[r["iid"]]["truth"][300 + r["t"]] != FX[r["iid"]]["truth"][300]})
    dd = pd.DataFrame(rows)
    if not len(dd):
        continue
    dd = dd.drop_duplicates(["iid", "t"])
    L.append(f"\n{model} agent:\n\n| subset | derivations | facts | correct % | answered % | tokens/derivation |\n|---|---|---|---|---|---|")
    grid = dd[(dd.t > 0) & (dd.t % 50 == 0)]
    parts = [("t = 0 (kept facts only: 100 % by construction)", dd[dd.t == 0]), ("all t > 0", dd[dd.t > 0]),
             ("t > 0, truth differs from s0", dd[(dd.t > 0) & dd.changed]), ("t > 0, truth equal to s0", dd[(dd.t > 0) & ~dd.changed]),
             ("t > 0 static", dd[(dd.t > 0) & (dd.slice == "static")]), ("t > 0 behaviour", dd[(dd.t > 0) & (dd.slice == "behav")])]
    parts += [(f"grid t = {t}", grid[grid.t == t]) for t in sorted(grid.t.unique())]
    o = {}
    for name, sub in parts:
        if len(sub):
            o[name] = {"n": len(sub), "acc": float(sub.correct.mean()), "tok": float(sub.tok.mean())}
            L.append(f"| {name} | {len(sub)} | {sub.iid.nunique()} | {pct(sub.correct.mean())} | {pct(sub.answered.mean())} | {sub.tok.mean() / 1000:.1f}k |")
    OUT["T6"][model] = o
L.append(f"\nRDE unit: the kept facts' own s0 derivation (27B): mean {np.mean([sum(f['derive_tokens']) for f in F]) / 1000:.1f}k tokens.")


# ------------------------------------------------------------------ taxonomy
def taxonomy(pol, sch="every"):
    d = REC[(REC.policy == pol) & (REC.schedule == sch)].sort_values(["iid", "t"])
    cats, fcats, ex = Counter(), defaultdict(set), defaultdict(list)
    for iid, x in d.groupby("iid"):
        origin, origin_ok = "s0", True
        for r in x.itertuples():
            if r.action in ("repair", "rederive"):
                origin, origin_ok = r.action, bool(r.served_valid)
            if r.served_valid:
                continue
            if not origin_ok and r.action not in ("repair", "rederive"):
                c = f"persisting wrong {origin}"
            elif r.action == "repair":
                c = "wrong in-place repair (accepted new answer wrong)"
            elif r.action == "rederive":
                c = "wrong re-derivation (agent answer wrong)"
            elif r.action == "same":
                c = "missed: evidence state unchanged (change outside the recorded evidence)"
            elif r.action == "memo":
                c = "missed: memoised still_valid reused on a state whose truth differs"
            elif r.action in ("valid", "unsure_fresh"):
                c = f"missed: judge said {r.verdict} on a changed state"
            else:
                c = r.action
            c += " | truth NONE" if FX[iid]["truth"][300 + int(r.t)] == "NONE" else " | truth present"
            cats[c] += 1
            fcats[c].add(iid)
            if len(ex[c]) < 6 and (not ex[c] or ex[c][-1][0] != iid):
                ex[c].append((iid, int(r.t), FX[iid]["K"][:50], str(r.served)[:50], FX[iid]["truth"][300 + int(r.t)][:50], str(getattr(r, "reason", ""))[:160]))
    return cats, fcats, ex


for pol in [FROZEN] + ([] if FROZEN == "ESM" else ["ESM"]):
    if (pol, "every") not in PF:
        continue
    cats, fcats, ex = taxonomy(pol)
    tot = sum(cats.values())
    nrec = len(REC[(REC.policy == pol) & (REC.schedule == "every")])
    OUT[f"taxonomy|{pol}"] = {k: {"reads": v, "facts": len(fcats[k])} for k, v in cats.items()}
    nf = REC[(REC.policy == pol) & (REC.schedule == "every")].iid.nunique()
    L.append(f"\n### T7. Error taxonomy of {pol}'s wrong-served reads ({nf} facts, every commit): {tot} of {nrec} reads\n")
    L.append("| cause | reads | % of wrong reads | facts | examples (fact, t, K, served, truth, judge reason) |\n|---|---|---|---|---|")
    for k, v in cats.most_common():
        exs = "; ".join(f"`{a}` t={b}: K={c!r} served={d!r} truth={e!r}" for a, b, c, d, e, _ in ex[k][:2])
        L.append(f"| {k} | {v} | {100 * v / max(tot, 1):.1f} | {len(fcats[k])} | {exs} |")
    OUT[f"taxonomy_examples|{pol}"] = {k: v for k, v in ex.items()}

# wrong-served reads of the frozen ESM by repo and by whether the oracle value is NONE
if len(REC) and (FROZEN, "every") in PF:
    w = REC[(REC.policy == FROZEN) & (REC.schedule == "every") & (~REC.served_valid)]
    tn = np.array([FX[i]["truth"][300 + int(t)] == "NONE" for i, t in zip(w.iid, w.t)])
    w = w.assign(tnone=tn, repo=[FX[i]["repo"] for i in w.iid])
    tab = w.groupby(["repo", "tnone"]).size().unstack(fill_value=0)
    L.append(f"\n### T7c. {FROZEN}'s wrong-served reads by repo: oracle value NONE vs present (ALL, every commit; {len(w)} reads, "
             f"{100 * tn.mean():.1f} % with oracle NONE)\n")
    L.append("| repo | wrong reads, oracle NONE | wrong reads, referent present |\n|---|---|---|")
    OUT["T7c"] = {}
    for repo, r in tab.sort_values(True if True in tab else tab.columns[0], ascending=False).iterrows():
        a, b = int(r.get(True, 0)), int(r.get(False, 0))
        OUT["T7c"][repo] = {"none": a, "present": b}
        L.append(f"| {repo} | {a} | {b} |")

# ------------------------------------------------------------------ repair verification statistics
L.append("\n### T7b. Repairs: judge proposals, verification, correctness (every commit)\n")
L.append("| policy | set | proposals | proposal correct % | verified accepted | accepted correct % | rejected | rejected-but-correct proposals |\n|---|---|---|---|---|---|---|---|")
OUT["T7b"] = {}
for pol in [v for v in ESMV]:
    d = REC[(REC.policy == pol) & (REC.schedule == "every")] if len(REC) else REC
    if not len(d) or "proposed_ok" not in d:
        continue
    p = d[d.proposed_ok >= 0]
    if not len(p):
        continue
    acc = p[p.verified == 1] if (p.verified >= 0).any() else p
    rej = p[p.verified == 0]
    o = {"proposals": len(p), "prop_ok": float(p.proposed_ok.mean()), "accepted": len(acc), "acc_ok": float(acc.proposed_ok.mean()) if len(acc) else np.nan,
         "rejected": len(rej), "rej_ok": int(rej.proposed_ok.sum())}
    OUT["T7b"][pol] = o
    L.append(f"| {pol} | {d.iid.nunique()} facts | {o['proposals']} | {pct(o['prop_ok'])} | {o['accepted']} | {pct(o['acc_ok'])} | {o['rejected']} | {o['rej_ok']} |")

# ------------------------------------------------------------------ dev calibration
L.append("\n### T8. Dev calibration of the repair policy (dev S1, 86 facts, every commit, 27B judge AND 27B re-deriver)\n")
dsim = DATA / "dev27" / "sim"
OUT["T8"] = {}
if dsim.exists() and list(dsim.glob("*.parquet")):
    from esm.envs.pyrepo import load_dev_facts
    DF = load_dev_facts()
    S1 = set(json.load(open(DEV_DATA / "sub_S1.json")))
    L.append(HDR)
    dpf = {}
    for p in sorted(dsim.glob("*__every.parquet")):
        pol = p.stem.split("__")[0]
        d = pd.read_parquet(p)
        pf = M.per_fact(d, DF)
        dpf[pol] = pf
        s = summ(pf, S1)
        OUT["T8"][pol] = s
        L.append(line(pol + " (27B deriver)", s))
        dd = d[d.proposed_ok >= 0] if "proposed_ok" in d else d.iloc[:0]
        if len(dd):
            OUT["T8"][pol]["proposals"] = {"n": len(dd), "ok": float(dd.proposed_ok.mean()),
                                           "accepted": int((dd.action == "repair").sum()), "accepted_ok": float(dd[dd.action == "repair"].repair_ok.mean()) if (dd.action == "repair").any() else None}
    # reference: dev stage (9B deriver)
    dev_sim = str(DEV_DATA / "sim")
    for pol in ("ESM", "ESM-norepair"):
        p = os.path.join(dev_sim, f"{pol}__every.parquet")
        if os.path.exists(p):
            pf = M.per_fact(pd.read_parquet(p), DF)
            s = summ(pf, S1)
            L.append(line(pol + " (dev stage, 9B deriver; reference)", s))
    L.append("\nPaired on S1 (27B deriver):\n\n| A − B | Δserved-wrong [CI] | Δtokens/fact [CI] |\n|---|---|---|")
    for a_, b_ in (("ESM-verify", "ESM"), ("ESM-verify", "ESM-norepair"), ("ESM", "ESM-norepair")):
        if a_ in dpf and b_ in dpf:
            ids = sorted(S1 & set(dpf[a_].index) & set(dpf[b_].index))
            r = M.paired(dpf[a_].loc[ids], dpf[b_].loc[ids])
            OUT["T8"][f"{a_}-{b_}"] = r
            L.append(f"| {a_} − {b_} | {100 * r['dsw']:+.1f} [{100 * r['dsw_ci'][0]:+.1f}, {100 * r['dsw_ci'][1]:+.1f}] "
                     f"| {r['dtok'] / 1000:+.1f}k [{r['dtok_ci'][0] / 1000:+.1f}, {r['dtok_ci'][1] / 1000:+.1f}] |")
    if (DATA / "frozen.json").exists():
        _fz = json.loads((DATA / "frozen.json").read_text())
        L.append(f"\nFrozen choice (pre-registered rule: {_fz['rule']}): **{_fz['policy']}**.")


# ------------------------------------------------------------------ curves
def curve(ids_name, sch="every", fname=None):
    ids_all = SUB.get(ids_name)
    if ids_all is None:
        return
    pts = []
    for (pol, s_), pf in PF.items():
        if s_ != sch or pol.startswith("DETECT"):
            continue
        ids = ids_all & set(pf.index)
        if len(ids) < len(ids_all):
            continue
        pts.append((pol, M.summary(with_setup(pol, pf).loc[sorted(ids)])))
    if len(pts) < 2:
        return
    OUT[f"curve|{ids_name}|{sch}"] = {p: {k: s[k] for k in ("ff", "fs", "sw", "tok_per_fact", "rde_sum", "tok_per_read")} for p, s in pts}
    fig, ax = plt.subplots(1, 2, figsize=(13, 5.2))
    for pol, s in pts:
        c = "C3" if pol.startswith("ESM") and "@oracle" not in pol else ("C7" if "@oracle" in pol else "C0")
        ax[0].scatter(100 * s["ff"], 100 * s["fs"], color=c, s=25)
        ax[0].annotate(pol, (100 * s["ff"], 100 * s["fs"]), fontsize=7)
        ax[1].scatter(max(s["rde_sum"], 1e-2), 100 * s["sw"], color=c, s=25)
        ax[1].annotate(pol, (max(s["rde_sum"], 1e-2), 100 * s["sw"]), fontsize=7)
    real = sorted([(max(s["rde_sum"], 1e-2), 100 * s["sw"], p) for p, s in pts if "@oracle" not in p])
    fr, best = [], 1e9
    for x, y, p in real:
        if y < best:
            fr.append((x, y)); best = y
    if fr:
        ax[1].step([a for a, _ in fr], [b for _, b in fr], where="post", color="k", lw=0.8, alpha=0.6)
    ax[0].set_xlabel("FF % (stored answer wrong, served)"); ax[0].set_ylabel("FS % (stored answer right, maintained)")
    ax[1].set_xscale("log"); ax[1].set_xlabel("cost: re-derivation-equivalents per fact (log)"); ax[1].set_ylabel("served-wrong % of reads")
    ax[0].set_title(f"FF–FS ({ids_name}, {sch})"); ax[1].set_title(f"served-wrong vs cost ({ids_name}, {sch}); red = ESM, blue = real baselines, grey = @oracle")
    fig.tight_layout()
    fig.savefig(RESULTS / (fname or f"curves_{ids_name}_{sch}.png"), dpi=130)
    plt.close(fig)


for nm in ("ALL", "H150"):
    for sch in ("every", "every20"):
        curve(nm, sch)

# re-derivation accuracy over time plot
if "27B" in OUT.get("T6", {}):
    rows = read_shards(DATA / "derivations.jsonl")
    dd = pd.DataFrame([{"t": r["t"], "correct": r["correct"], "iid": r["iid"]} for r in rows if r["iid"] in FX and r["t"] > 0])
    if len(dd):
        dd["bin"] = (dd.t - 1) // 50 * 50 + 50
        g = dd.groupby("bin").correct.agg(["mean", "size"])
        fig, ax = plt.subplots(figsize=(6, 4))
        ax.plot(g.index, 100 * g["mean"], "o-", color="C3", label="27B re-derivations (all, binned by t)")
        p9 = DATA / "derivations_9b.jsonl"
        if True:
            r9 = read_shards(p9)
            d9 = pd.DataFrame([{"t": r["t"], "correct": r["correct"]} for r in r9 if r["iid"] in FX and r["t"] > 0])
            if len(d9):
                d9["bin"] = (d9.t - 1) // 50 * 50 + 50
                g9 = d9.groupby("bin").correct.mean()
                ax.plot(g9.index, 100 * g9, "s--", color="C0", label="9B re-derivations")
        ax.set_xlabel("commit t (bin end)"); ax.set_ylabel("correct %"); ax.set_ylim(0, 100); ax.legend(fontsize=8)
        ax.set_title("re-derivation accuracy over time (held-out)")
        fig.tight_layout(); fig.savefig(RESULTS / "rederivation_accuracy.png", dpi=130); plt.close(fig)

(RESULTS / "tables.md").write_text("\n".join(L), encoding="utf-8")
(RESULTS / "results.json").write_text(json.dumps(OUT, indent=1, default=lambda o: o.item() if hasattr(o, "item") else str(o)), encoding="utf-8")
print("written", RESULTS / "tables.md")
